from __future__ import annotations

from jammate_engine.core.voicing import ColorPolicyMode, ContentFamily, Disposition, RootSupportPolicy, VoicingPolicy


def get_voicing_policy() -> VoicingPolicy:
    return VoicingPolicy(
        root_support=RootSupportPolicy.ROOTLESS_ALLOWED,
        allowed_content=(
            ContentFamily.ROOTED_COLOR,
            ContentFamily.ROOTLESS_A,
            ContentFamily.ROOTLESS_B,
            ContentFamily.SEVENTH_BASIC,
        ),
        preferred_content=ContentFamily.ROOTED_COLOR,
        content_family_weights={
            ContentFamily.ROOTED_COLOR.value: 0.28,
            ContentFamily.ROOTLESS_A.value: 0.10,
            ContentFamily.ROOTLESS_B.value: 0.04,
            ContentFamily.SEVENTH_BASIC.value: -0.12,
        },
        source_family_weights={},
        source_family_weights_by_gate={
            "chord_symbol_only": {
                "root_third_fifth_root": 0.02,
                "third_fifth_root_third": 0.02,
                "fifth_root_third_fifth": 0.00,
                "root_second_fifth_root": 0.03,
                "second_fifth_root_second": 0.02,
                "fifth_root_second_fifth": 0.00,
                "root_fourth_fifth_root": 0.03,
                "fourth_fifth_root_fourth": 0.02,
                "fifth_root_fourth_fifth": 0.00,
                "root_third_fifth": 0.02,
                "root_second_fifth": 0.02,
                "root_fourth_fifth": 0.02,
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.08,
                # Ballad should not over-reward plain 1357, but it remains a
                # valid conservative anchor before expansion adds warm color.
                "root_third_fifth_seventh": -0.04,
                "root_third_fifth_sixth": -0.03,
                "root_fourth_fifth_seventh": -0.05,
            },
            "harmonic_expansion": {
                "root_third_sixth": 0.14,
                "root_third_ninth": 0.16,
                "root_third_seventh": 0.10,
                "third_seventh_ninth": 0.08,
                "third_seventh_eleventh": 0.04,
                "third_seventh_thirteenth": 0.06,
                "third_seventh_altered_color": 0.06,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.10,
                # Ballad is intentionally warm/rooted under expansion.  Rooted
                # color receives the strongest source-level prior; rootless is
                # still available but secondary until explicit chart color asks
                # for it.
                "root_third_fifth_ninth": 0.24,
                "root_third_seventh_ninth": 0.24,
                "root_third_sixth_ninth": 0.22,
                "root_third_seventh_thirteenth": 0.18,
                "root_third_seventh_eleventh": 0.08,
                "with_5": 0.06,
                "third_fifth_seventh_ninth": 0.06,
                "with_13": -0.04,
                "third_thirteenth_seventh_ninth": -0.04,
                "third_fifth_seventh_eleventh": 0.00,
                "third_eleventh_fifth_seventh": 0.00,
                "third_seventh_ninth_eleventh": 0.02,
                "root_third_seventh_altered_color": 0.06,
                "altered_dominant_rootless": 0.06,
                "third_seventh_altered_color_a_altered_color_b": 0.06,
            },
            "explicit_chart_color": {
                "root_third_sixth": 0.16,
                "root_third_ninth": 0.18,
                "root_second_fifth": 0.06,
                "root_fourth_fifth": 0.06,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": 0.08,
                "third_seventh_thirteenth": 0.10,
                "third_seventh_altered_color": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.08,
                "root_third_fifth_ninth": 0.22,
                "root_third_seventh_ninth": 0.22,
                "root_third_sixth_ninth": 0.22,
                "root_third_seventh_thirteenth": 0.20,
                "root_third_seventh_eleventh": 0.10,
                "with_5": 0.08,
                "third_fifth_seventh_ninth": 0.08,
                "with_13": 0.02,
                "third_thirteenth_seventh_ninth": 0.02,
                "third_thirteenth_seventh_fifth": 0.04,
                "third_fifth_seventh_eleventh": 0.04,
                "third_eleventh_fifth_seventh": 0.04,
                "third_seventh_ninth_eleventh": 0.06,
                "root_third_seventh_altered_color": 0.10,
                "altered_dominant_rootless": 0.10,
                "third_seventh_altered_color_a_altered_color_b": 0.10,
            },
            "explicit_chart_color_plus_harmonic_expansion": {
                "root_third_sixth": 0.16,
                "root_third_ninth": 0.18,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": 0.08,
                "third_seventh_thirteenth": 0.10,
                "third_seventh_altered_color": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.08,
                "root_third_fifth_ninth": 0.24,
                "root_third_seventh_ninth": 0.24,
                "root_third_sixth_ninth": 0.22,
                "root_third_seventh_thirteenth": 0.20,
                "root_third_seventh_eleventh": 0.10,
                "with_5": 0.08,
                "third_fifth_seventh_ninth": 0.08,
                "with_13": 0.00,
                "third_thirteenth_seventh_ninth": 0.00,
                "third_thirteenth_seventh_fifth": 0.02,
                "third_fifth_seventh_eleventh": 0.04,
                "third_eleventh_fifth_seventh": 0.04,
                "third_seventh_ninth_eleventh": 0.06,
                "root_third_seventh_altered_color": 0.10,
                "altered_dominant_rootless": 0.10,
                "third_seventh_altered_color_a_altered_color_b": 0.10,
            },
        },
        low_priority_degrees=("#9", "b13"),
        low_priority_degree_penalty=0.12,
        harmonic_expansion_enabled=True,
        color_policy_mode=ColorPolicyMode.STYLE_SAFE_EXTENSIONS,
        preferred_disposition=Disposition.SPREAD,
        allowed_dispositions=(Disposition.SPREAD, Disposition.TWO_HAND_SPREAD, Disposition.OPEN),
        preferred_density=5,
        min_density=4,
        max_density=6,
        register_low=45,
        register_high=80,
        left_hand_low=38,
        left_hand_high=58,
        right_hand_low=55,
        right_hand_high=80,
        top_voice_low=62,
        top_voice_high=77,
        comfort_register_low=55,
        comfort_register_high=72,
        max_voicing_span=28,
        max_top_voice_leap=7,
        voice_leading_weight=1.25,
        top_voice_weight=1.35,
        register_guard_weight=1.05,
        selector_temperature=0.10,
        selection_pool_size=4,
        metadata={
            "style": "jazz_ballad",
            "default_texture": "warm_spread_sustain_with_controlled_color",
            "milestone": "v2_1_43_closed_source_weight_finalization",
            "voicing_intent": "5_note_2_plus_3_or_spread_rooted_color_with_rootless_options",
            "density_rule": "default_4_5_common_5_rich_6_special_7_future_only",
            "content_bias": "rooted_color_preferred_rootless_options_available_seventh_basic_deemphasized",
            "harmonic_expansion_role": "ballad intentionally opens style-safe color for plain seventh chords; this is not the global chord-symbol-only default",
            "harmonic_expansion_target_families": [ContentFamily.ROOTED_COLOR.value],
            "disposition_method_weights": {
                "family": {"closed": 0.20, "open": 0.35, "spread": 0.45},
                "open": {"generic_open": 0.30, "drop2": 0.34, "drop3": 0.25, "drop2_and_4": 0.11},
                "spread": {"lower_upper_grouped": 0.36, "foundation_projection": 0.32, "root_anchored": 0.22, "root_10th_projection": 0.10},
            },
            "disposition_method_weight_contract": "planning_only_v2_2_10; not consumed by selector yet",
            "ballad_spread_runtime_pilot": {
                "version": "v2_2_44",
                "enabled": False,
                "scene": "warm_spread_phrase",
                "contract_ids": [
                    "spread_1plus3_contract",
                    "spread_1plus4_contract",
                    "spread_2plus3_contract",
                    "spread_2plus4_contract",
                    "spread_3plus3_contract",
                ],
                "preferred_contract_ids": ["spread_1plus4_contract", "spread_2plus3_contract"],
                "runtime_boundary": "planning_contract_only_not_consumed_by_style_runtime",
            },
            "ballad_spread_runtime_safe_dry_run": {
                "version": "v2_2_44",
                "dry_run_enabled": False,
                "chain": "entry_contract_to_selector_gate_to_notes_only_candidate_to_future_conversion_boundary",
                "candidate_conversion_allowed": False,
                "style_runtime_wiring_enabled": False,
                "runtime_enabled": False,
            },
            "ballad_spread_runtime_conversion_boundary_audit": {
                "version": "v2_2_45",
                "boundary_audit_enabled": True,
                "conversion_allowed": False,
                "candidate_generator_wiring_allowed": False,
                "style_runtime_wiring_enabled": False,
                "runtime_enabled": False,
                "target": "SpreadProjectionCandidate_to_VoicingCandidate_boundary_audit_only",
            },
            "functional_grouping_1plus4_contract_alignment": {
                "version": "v2_2_46",
                "runtime_grouping_value_exists": True,
                "projection_map_supported": True,
                "group_roles": ["foundation", "projection"],
                "candidate_conversion_allowed": False,
                "candidate_generator_wiring_allowed": False,
                "style_runtime_wiring_enabled": False,
                "runtime_enabled": False,
                "target": "FunctionalGrouping.ONE_PLUS_FOUR_contract_alignment_only",
            },
            "spread_runtime_adapter_skeleton": {
                "version": "v2_2_47",
                "adapter_skeleton_exists": True,
                "adapter_conversion_allowed": False,
                "candidate_generator_wiring_allowed": False,
                "style_runtime_wiring_enabled": False,
                "runtime_enabled": False,
                "target": "SpreadProjectionCandidate_to_VoicingCandidate_adapter_skeleton_only",
            },
            "ballad_spread_runtime_candidate_pool": {
                "version": "v2_2_48",
                "candidate_pool_enabled": False,
                "adapter_conversion_allowed": False,
                "candidate_pool_merge_allowed": False,
                "candidate_generator_wiring_allowed": False,
                "fallback_to_existing_pool": True,
                "style_runtime_default_enabled": False,
                "default_style_runtime_unchanged": True,
                "runtime_enabled": False,
                "target": "explicit_ballad_spread_pilot_candidate_pool_only",
            },
            "ballad_spread_pilot_selection_weight_fallback_audit": {
                "version": "v2_2_49",
                "audit_enabled": True,
                "fallback_required": True,
                "max_spread_candidate_share": 0.35,
                "max_spread_score_margin": 0.15,
                "candidate_order_is_selection_priority": False,
                "selector_scoring_still_authoritative": True,
                "candidate_selection_not_performed": True,
                "style_runtime_default_enabled": False,
                "default_style_runtime_unchanged": True,
                "runtime_enabled": False,
                "target": "selection_weight_and_fallback_audit_only",
            },
            "ballad_spread_pilot_runtime_enablement_guard": {
                "version": "v2_2_50",
                "runtime_guard_enabled": False,
                "listening_isolation_enabled": False,
                "candidate_pool_enabled": False,
                "fallback_required": True,
                "first_listening_isolation_only": True,
                "style_runtime_default_enabled": False,
                "default_style_runtime_unchanged": True,
                "candidate_generator_wiring_allowed": False,
                "runtime_pilot_enabled": False,
                "runtime_enabled": False,
                "target": "explicit_ballad_spread_first_listening_isolation_only",
            },
            "ballad_spread_1plus3_pilot": {
                "version": "v2_2_56",
                "enabled": False,
                "required_recipe_id": "spread_1plus3_contract",
                "target": "explicit_ballad_spread_1plus3_listening_isolation_only",
                "style_runtime_default_enabled": False,
                "runtime_enabled": False,
            },
            "ballad_spread_2plus3_pilot": {
                "version": "v2_2_57",
                "enabled": False,
                "required_recipe_id": "spread_2plus3_contract",
                "dual_demo_required": True,
                "expanded_demo_target_ratio": 0.60,
                "target": "explicit_ballad_spread_2plus3_listening_isolation_only",
                "style_runtime_default_enabled": False,
                "runtime_enabled": False,
            },
            "ballad_spread_1plus4_true_isolation": {
                "version": "v2_2_52",
                "enabled": False,
                "required_recipe_id": "spread_1plus4_contract",
                "fallback_only_when_missing": True,
                "candidate_pool_mode": "spread_only_when_available",
                "style_runtime_default_enabled": False,
                "default_style_runtime_unchanged": True,
                "runtime_enabled": False,
                "target": "explicit_ballad_spread_1plus4_listening_isolation_only",
            },
            "source_balance_contract": "3_and_4_note_closed_source_weight_contract: four_mode_aware; ballad favors rooted color during expansion while chart-written color still gets fidelity boost",
            "upper_structure_register_refinement": {
                "version": "v2_2_89",
                "purpose": "ballad keeps upper-structure altered color warm rather than sharp",
                "top_soft_high": 74,
                "top_hard_high": 77,
                "average_pitch_soft_high": 68,
                "single_low_note_guard_threshold": 40,
                "max_notes_below_threshold": 1,
            },
            "upper_structure_register_refinement_enabled": True,
            "upper_structure_top_soft_high": 74,
            "upper_structure_top_hard_high": 77,
            "upper_structure_average_pitch_soft_high": 68,
            "low_register_single_note_threshold": 40,
            "max_notes_below_low_register_single_note_threshold": 1,
            "voicing_register_continuity_guard_enabled": True,
            "voicing_register_center_target": 64,
            "voicing_register_center_tolerance": 4,
            "voicing_register_top_soft_high": 74,
            "voicing_register_top_hard_high": 77,
            "voicing_register_low_soft_low": 43,
            "voicing_register_low_hard_low": 40,
            "voicing_register_top_motion_soft_limit": 4,
            "voicing_register_average_motion_soft_limit": 3.5,
            "voicing_register_continuity_weight": 1.15,
            "altered_dominant_source_weight_calibration": {
                "version": "v2_2_88",
                "purpose": "style default intensity/profile for legal altered dominant source selection",
                "default_intensity": "medium",
                "default_scopes": ['resolving_v7', 'secondary_dominants'],
                "source_kinds": ["rooted_color", "rootless_ab", "upper_structure"],
            },
            "altered_dominant_source_weight_biases_by_intensity": {'light': {'rooted_color': 0.06, 'rootless_ab': -0.06, 'upper_structure': -0.06}, 'medium': {'rooted_color': 0.14, 'rootless_ab': 0.04, 'upper_structure': 0.06}, 'high': {'rooted_color': 0.22, 'rootless_ab': 0.1, 'upper_structure': 0.14}, 'full': {'rooted_color': 0.3, 'rootless_ab': 0.18, 'upper_structure': 0.22}},
        },
    )
