from __future__ import annotations

from jammate_engine.core.voicing import ColorPolicyMode, ContentFamily, Disposition, RootSupportPolicy, VoicingPolicy


def get_voicing_policy() -> VoicingPolicy:
    return VoicingPolicy(
        root_support=RootSupportPolicy.ROOTLESS_ALLOWED,
        allowed_content=(
            ContentFamily.ROOTED_COLOR,
            ContentFamily.ROOTLESS_A,
            ContentFamily.ROOTLESS_B,
            ContentFamily.SEVENTH_BASIC,
        ),
        preferred_content=ContentFamily.ROOTED_COLOR,
        content_family_weights={
            ContentFamily.ROOTED_COLOR.value: 0.28,
            ContentFamily.ROOTLESS_A.value: 0.10,
            ContentFamily.ROOTLESS_B.value: 0.04,
            ContentFamily.SEVENTH_BASIC.value: -0.12,
        },
        source_family_weights={},
        source_family_weights_by_gate={
            "chord_symbol_only": {
                "root_third_fifth_root": 0.02,
                "third_fifth_root_third": 0.02,
                "fifth_root_third_fifth": 0.00,
                "root_second_fifth_root": 0.03,
                "second_fifth_root_second": 0.02,
                "fifth_root_second_fifth": 0.00,
                "root_fourth_fifth_root": 0.03,
                "fourth_fifth_root_fourth": 0.02,
                "fifth_root_fourth_fifth": 0.00,
                "root_third_fifth": 0.02,
                "root_second_fifth": 0.02,
                "root_fourth_fifth": 0.02,
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.08,
                # Ballad should not over-reward plain 1357, but it remains a
                # valid conservative anchor before expansion adds warm color.
                "root_third_fifth_seventh": -0.04,
                "root_third_fifth_sixth": -0.03,
                "root_fourth_fifth_seventh": -0.05,
            },
            "harmonic_expansion": {
                "root_third_sixth": 0.14,
                "root_third_ninth": 0.16,
                "root_third_seventh": 0.10,
                "third_seventh_ninth": 0.08,
                "third_seventh_eleventh": 0.04,
                "third_seventh_thirteenth": 0.06,
                "third_seventh_altered_color": 0.06,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.10,
                # Ballad is intentionally warm/rooted under expansion.  Rooted
                # color receives the strongest source-level prior; rootless is
                # still available but secondary until explicit chart color asks
                # for it.
                "root_third_fifth_ninth": 0.24,
                "root_third_seventh_ninth": 0.24,
                "root_third_sixth_ninth": 0.22,
                "root_third_seventh_thirteenth": 0.18,
                "root_third_seventh_eleventh": 0.08,
                "with_5": 0.06,
                "third_fifth_seventh_ninth": 0.06,
                "with_13": -0.04,
                "third_thirteenth_seventh_ninth": -0.04,
                "third_fifth_seventh_eleventh": 0.00,
                "third_eleventh_fifth_seventh": 0.00,
                "third_seventh_ninth_eleventh": 0.02,
                "root_third_seventh_altered_color": 0.06,
                "altered_dominant_rootless": 0.06,
                "third_seventh_altered_color_a_altered_color_b": 0.06,
            },
            "explicit_chart_color": {
                "root_third_sixth": 0.16,
                "root_third_ninth": 0.18,
                "root_second_fifth": 0.06,
                "root_fourth_fifth": 0.06,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": 0.08,
                "third_seventh_thirteenth": 0.10,
                "third_seventh_altered_color": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.08,
                "root_third_fifth_ninth": 0.22,
                "root_third_seventh_ninth": 0.22,
                "root_third_sixth_ninth": 0.22,
                "root_third_seventh_thirteenth": 0.20,
                "root_third_seventh_eleventh": 0.10,
                "with_5": 0.08,
                "third_fifth_seventh_ninth": 0.08,
                "with_13": 0.02,
                "third_thirteenth_seventh_ninth": 0.02,
                "third_thirteenth_seventh_fifth": 0.04,
                "third_fifth_seventh_eleventh": 0.04,
                "third_eleventh_fifth_seventh": 0.04,
                "third_seventh_ninth_eleventh": 0.06,
                "root_third_seventh_altered_color": 0.10,
                "altered_dominant_rootless": 0.10,
                "third_seventh_altered_color_a_altered_color_b": 0.10,
            },
            "explicit_chart_color_plus_harmonic_expansion": {
                "root_third_sixth": 0.16,
                "root_third_ninth": 0.18,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": 0.08,
                "third_seventh_thirteenth": 0.10,
                "third_seventh_altered_color": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.08,
                "root_third_fifth_ninth": 0.24,
                "root_third_seventh_ninth": 0.24,
                "root_third_sixth_ninth": 0.22,
                "root_third_seventh_thirteenth": 0.20,
                "root_third_seventh_eleventh": 0.10,
                "with_5": 0.08,
                "third_fifth_seventh_ninth": 0.08,
                "with_13": 0.00,
                "third_thirteenth_seventh_ninth": 0.00,
                "third_thirteenth_seventh_fifth": 0.02,
                "third_fifth_seventh_eleventh": 0.04,
                "third_eleventh_fifth_seventh": 0.04,
                "third_seventh_ninth_eleventh": 0.06,
                "root_third_seventh_altered_color": 0.10,
                "altered_dominant_rootless": 0.10,
                "third_seventh_altered_color_a_altered_color_b": 0.10,
            },
        },
        low_priority_degrees=("#9", "b13", "#11"),
        low_priority_degree_penalty=0.12,
        harmonic_expansion_enabled=True,
        color_policy_mode=ColorPolicyMode.STYLE_SAFE_EXTENSIONS,
        preferred_disposition=Disposition.SPREAD,
        allowed_dispositions=(Disposition.SPREAD, Disposition.TWO_HAND_SPREAD, Disposition.OPEN),
        preferred_density=5,
        min_density=4,
        max_density=6,
        register_low=45,
        register_high=80,
        left_hand_low=38,
        left_hand_high=58,
        right_hand_low=55,
        right_hand_high=80,
        top_voice_low=62,
        top_voice_high=77,
        comfort_register_low=55,
        comfort_register_high=72,
        max_voicing_span=28,
        max_top_voice_leap=7,
        voice_leading_weight=1.25,
        top_voice_weight=1.35,
        register_guard_weight=1.05,
        selector_temperature=0.10,
        selection_pool_size=4,
        metadata={
            "style": "jazz_ballad",
            "default_texture": "warm_spread_sustain_with_controlled_color",
            "milestone": "v2_6_30_ballad_spread_1plus4_lower_foundation_calibration",
            "voicing_intent": "5_6_note_grouped_spread_rooted_color_6_to_4_with_low_frequency_1plus4_color",
            "density_rule": "4_note_spread_retired; ordinary Ballad spread runtime centers on 2+3/2+4/3+3 with low-frequency 1+4 upper4 color lane",
            "spread_density_system_reset_version": "v2_6_10",
            "spread_legacy_4note_groupings_retired": True,
            "spread_retired_four_note_groupings": ["1+3", "2+2"],
            "spread_density_runtime_contract_ids": [
                "spread_1plus4_contract",
                "spread_2plus3_contract",
                "spread_2plus4_contract",
                "spread_3plus3_contract",
            ],
            "content_bias": "rooted_color_preferred_rootless_options_available_seventh_basic_deemphasized",
            "harmonic_expansion_role": "ballad intentionally opens style-safe color for plain seventh chords; this is not the global chord-symbol-only default",
            "safe_extension_color_gate": {
                "version": "v2_6_11",
                "major_seventh_default_colors": ["9", "13"],
                "major_seventh_sharp11": "explicit_symbol_or_harmonic_color_intent_only",
                "reason": "warm Ballad maj7 expansion should prefer 9/13; unnotated #11 is a Lydian/bright color, not default safe warmth",
            },
            "harmonic_expansion_target_families": [ContentFamily.ROOTED_COLOR.value],
            "disposition_method_weights": {
                "family": {"closed": 0.20, "open": 0.35, "spread": 0.45},
                "open": {"generic_open": 0.30, "drop2": 0.34, "drop3": 0.25, "drop2_and_4": 0.11},
                "spread": {"lower_upper_grouped": 0.36, "foundation_projection": 0.32, "root_anchored": 0.22, "root_10th_projection": 0.10},
            },
            "disposition_method_weight_contract": "planning_only_v2_2_10; not consumed by selector yet",
            "ballad_spread_grouping_mix_policy": {
                "version": "v2_6_30",
                "enabled": True,
                "weight_cycle": 100,
                "weights_by_scene": {
                    "normal_comping": {
                        "spread_1plus4_contract": 4,
                        "spread_2plus3_contract": 76,
                        "spread_2plus4_contract": 16,
                        "spread_3plus3_contract": 4,
                        "spread_3plus4_contract": 0
                    },
                    "chorus_lift": {
                        "spread_1plus4_contract": 3,
                        "spread_2plus3_contract": 53,
                        "spread_2plus4_contract": 28,
                        "spread_3plus3_contract": 14,
                        "spread_3plus4_contract": 2
                    },
                    "ending_climax": {
                        "spread_1plus4_contract": 0,
                        "spread_2plus3_contract": 22,
                        "spread_2plus4_contract": 30,
                        "spread_3plus3_contract": 35,
                        "spread_3plus4_contract": 13
                    }
                },
                "retired_four_note_contracts": ["spread_1plus3_contract", "spread_2plus2_contract"],
                "runtime_boundary": "ballad_grouped_spread_density_route",
                "one_plus_four_default_role": "low_frequency_upper4_color_lane; not a high-frequency comping body"
            },
            "spread_runtime_adapter_emit_all_candidates": True,
            "spread_emit_all_candidates_for_groupwise_selection": True,
            "spread_groupwise_voice_leading_runtime_enabled": True,
            "spread_grouping_mix_selected_6note_contract_bias": 3.0,
            "ballad_spread_5_to_6_density_ratio_target": {
                "version": "v2_6_30",
                "target": "5-note:6-note ~= 6:4 with 1+4 restored at low frequency",
                "scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "four_note_spread_remains_retired": True,
                "seven_note_remains_low_frequency": True,
            },
            "ballad_spread_listening_calibration": {
                "version": "v2_6_30",
                "scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "ordinary_runtime_groupings": ["2+3", "2+4", "3+3", "1+4_low_frequency"],
                "one_plus_four_role": "upper4 color lane restored at low frequency, not a default high-frequency comping body",
                "target_one_plus_four_events_per_misty_three_choruses": "4_to_10",
                "reason": "5-note body should still read as stable 2+3 foundation/projection while 1+4 appears as occasional upper-block color",
            },
            "ballad_spread_top_voice_register_micro_calibration": {
                "version": "v2_6_28",
                "scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "target": "avoid opening/isolated upper projection directly hitting the top ceiling",
                "density_lane_unchanged": True,
                "one_plus_four_restored_low_frequency": True,
            },
            "spread_top_register_micro_calibration_enabled": True,
            "spread_top_register_micro_calibration_version": "v2_6_28",
            "ballad_spread_1plus4_lower_foundation_calibration": {
                "version": "v2_6_30",
                "scope": "voicing_only",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "one_plus_four_target": "low_frequency_4_to_10_events_per_misty_three_choruses",
                "one_plus_four_target_events_per_196": "4_to_10",
                "lower_foundation_guard": "lower group span stays within one octave; low-register thickness remains audited",
                "lower_foundation_span_limit_semitones": 12,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_lower_upper_gap_weight_balance": {
                "version": "v2_6_31",
                "scope": "voicing_only_audit_and_guardrail",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "keeps_density_lane_unchanged": True,
                "keeps_1plus4_low_frequency": True,
                "tracks_lower_upper_gap_by_grouping_density_and_recipe": True,
                "gap_comfort_band_semitones": [2, 7],
                "current_misty_three_chorus_observation": {
                    "tight_gap_events": "2+4 sparse audit flag",
                    "wide_gap_events": "2+3 sparse audit flag",
                    "density_target_preserved": "5-note:6-note ~= 6:4",
                },
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_gap_aware_candidate_scope_micro_calibration": {
                "version": "v2_6_33",
                "scope": "voicing_only_same_recipe_candidate_micro_bias",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "targets": ["2+4_tight_gap_outliers", "2+3_wide_gap_outliers"],
                "same_recipe_only": True,
                "keeps_density_lane_unchanged": True,
                "keeps_1plus4_low_frequency": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_wide_gap_deferred_outlier_strategy": {
                "version": "v2_6_33",
                "scope": "voicing_only_same_recipe_wide_gap_deferred_micro_bias",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "target": "remaining 2+3 Fm7 wide gap outliers from v2_6_32",
                "same_recipe_only": True,
                "not_broad_scorer": True,
                "keeps_density_lane_unchanged": True,
                "keeps_1plus4_low_frequency": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_2plus3_wide_gap_source_inventory_plan": {
                "version": "v2_6_34",
                "scope": "voicing_only_source_inventory_plan_and_audit",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "target": "remaining 2+3 Fm7 wide gap outliers from v2_6_33",
                "same_recipe_only": True,
                "not_broad_scorer": True,
                "runtime_replacement_enabled": False,
                "reason": "direct replacement fixes local gap but cascades density lane",
                "recommended_next_boundary": "phrase_scope_or_inventory_level_candidate_availability_not_runtime_replacement",
                "keeps_density_lane_unchanged": True,
                "keeps_1plus4_low_frequency": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_phrase_scope_wide_gap_candidate_availability": {
                "version": "v2_6_35",
                "scope": "voicing_only_phrase_scope_candidate_availability",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "target": "remaining 2+3 Fm7 wide gap outliers from v2_6_34",
                "same_recipe_only": True,
                "not_broad_scorer": True,
                "uses_top_stable_candidate": True,
                "state_advance_protected": True,
                "runtime_realization_enabled": True,
                "keeps_density_lane_unchanged": True,
                "keeps_1plus4_low_frequency": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_phrase_state_boundary_regression_review": {
                "version": "v2_6_36",
                "scope": "voicing_only_phrase_state_boundary_audit",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection only",
                "target": "state-protected events introduced by v2_6_35",
                "observational_only": True,
                "no_runtime_candidate_change": True,
                "checks_next_event_uses_state_anchor": True,
                "checks_realized_notes_not_used_as_state": True,
                "keeps_density_lane_unchanged": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_phrase_state_boundary_helper_cleanup": {
                "version": "v2_6_37",
                "scope": "voicing_only_runtime_state_anchor_helper_cleanup",
                "runtime_scope": "core voicing resolver state advancement",
                "target": "centralize realized-notes versus state-anchor separation validated in v2_6_35/v2_6_36",
                "behavior_preserving": True,
                "no_runtime_candidate_change": True,
                "helper_owner": "VoicingStateAdvanceAnchor",
                "selector_declares_anchor": True,
                "resolver_consumes_anchor": True,
                "keeps_density_lane_unchanged": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "ballad_spread_post_continuity_listening_checkpoint": {
                "version": "v2_6_39",
                "scope": "voicing_checkpoint_after_ballad_continuity_bugfix",
                "runtime_scope": "Jazz Ballad SPREAD grouped voicing selection plus accepted Ballad continuity patch audit",
                "observational_only": True,
                "no_runtime_candidate_change": True,
                "confirms_v2_6_38_problem_bars": [41, 63, 95],
                "confirms_state_anchor_boundary": True,
                "keeps_density_lane_unchanged": True,
                "keeps_1plus4_low_frequency": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "spread_top_register_micro_soft_high": 74,
            "spread_top_register_micro_hard_high": 76,
            "spread_top_register_micro_average_soft_high": 66,
            "spread_top_register_micro_weight": 1.4,
            "spread_top_register_micro_soft_penalty": 0.70,
            "spread_top_register_micro_hard_penalty": 1.60,
            "spread_top_register_micro_average_penalty": 0.25,
            "spread_lower_foundation_quality_gate_enabled": True,
            "spread_lower_2note_foundation_mode": "rooted",
            "spread_lower_2note_rootless_is_separate_mode": True,
            "spread_lower_2note_foundation_lock_enabled": True,
            "spread_lower_2note_recipe_change_penalty": 6.0,
            "spread_rooted_bass_anchor_enabled": True,
            "spread_root_bass_anchor_low": 40,
            "spread_root_bass_anchor_high": 52,
            "spread_root_bass_anchor_target": 47,
            "spread_root_bass_anchor_high_tail_semitones": 4,
            "spread_root_bass_anchor_high_tail_max_lower_span": 12,
            "spread_whole_register_low": 40,
            "spread_whole_register_high": 78,
            "spread_whole_register_target_span": 30,
            "spread_lower_2note_low": 40,
            "spread_lower_2note_high": 58,
            "spread_lower_2note_target_low": 40,
            "spread_lower_2note_min_top": 0,
            "spread_upper_low": 50,
            "spread_upper_high": 77,
            "spread_upper_target_low": 57,
            "spread_min_group_gap": 1,
            "spread_max_group_gap": 7,
            "spread_gap_aware_candidate_scope_micro_calibration_enabled": True,
            "spread_gap_aware_candidate_scope_micro_calibration_version": "v2_6_33",
            "spread_gap_aware_comfort_min": 2,
            "spread_gap_aware_comfort_max": 7,
            "spread_gap_aware_same_recipe_max_primary_cost_delta": 3.3,
            "spread_wide_gap_deferred_outlier_strategy_enabled": True,
            "spread_wide_gap_deferred_outlier_strategy_version": "v2_6_33",
            "spread_wide_gap_deferred_same_recipe_max_primary_cost_delta": 4.8,
            "spread_wide_gap_source_inventory_plan_enabled": True,
            "spread_wide_gap_source_inventory_plan_version": "v2_6_34",
            "spread_wide_gap_source_inventory_runtime_replacement_enabled": False,
            "spread_phrase_scope_wide_gap_candidate_availability_enabled": True,
            "spread_phrase_scope_wide_gap_candidate_availability_version": "v2_6_35",
            "spread_phrase_scope_wide_gap_state_advance_protection_enabled": True,
            "spread_phrase_state_boundary_regression_review_enabled": True,
            "spread_phrase_state_boundary_regression_review_version": "v2_6_36",
            "spread_phrase_state_boundary_regression_review_observational_only": True,
            "spread_phrase_state_boundary_helper_cleanup_enabled": True,
            "spread_phrase_state_boundary_helper_cleanup_version": "v2_6_37",
            "spread_phrase_state_boundary_helper_cleanup_behavior_preserving": True,
            "ballad_spread_post_continuity_listening_checkpoint_enabled": True,
            "ballad_spread_post_continuity_listening_checkpoint_version": "v2_6_39",
            "ballad_spread_post_continuity_listening_checkpoint_observational_only": True,
            "spread_max_overall_span": 39,
            "spread_runtime_adapter": {
                "version": "v2_6_22",
                "adapter_conversion_allowed": True,
                "target": "grouped_spread_runtime_candidate_pool_only",
            },
            "retired_spread_pilot_logic_cleanup": {
                "version": "v2_6_22",
                "removed": [
                    "ballad_spread_runtime_pilot",
                    "ballad_spread_runtime_safe_dry_run",
                    "ballad_spread_runtime_candidate_pool",
                    "ballad_spread_pilot_runtime_enablement_guard",
                    "ballad_spread_1plus3_pilot",
                    "ballad_spread_1plus4_true_isolation",
                ],
                "current_runtime": "grouped_spread_runtime_candidate_pool",
            },
            "source_balance_contract": "3_and_4_note_closed_source_weight_contract: four_mode_aware; ballad favors rooted color during expansion while chart-written color still gets fidelity boost",
            "upper_structure_register_refinement": {
                "version": "v2_2_89",
                "purpose": "ballad keeps upper-structure altered color warm rather than sharp",
                "top_soft_high": 74,
                "top_hard_high": 77,
                "average_pitch_soft_high": 68,
                "single_low_note_guard_threshold": 40,
                "max_notes_below_threshold": 1,
            },
            "upper_structure_register_refinement_enabled": True,
            "upper_structure_top_soft_high": 74,
            "upper_structure_top_hard_high": 77,
            "upper_structure_average_pitch_soft_high": 68,
            "low_register_single_note_threshold": 40,
            "max_notes_below_low_register_single_note_threshold": 1,
            "voicing_register_continuity_guard_enabled": True,
            "voicing_register_center_target": 64,
            "voicing_register_center_tolerance": 4,
            "voicing_register_top_soft_high": 74,
            "voicing_register_top_hard_high": 77,
            "voicing_register_low_soft_low": 43,
            "voicing_register_low_hard_low": 40,
            "voicing_register_top_motion_soft_limit": 4,
            "voicing_register_average_motion_soft_limit": 3.5,
            "voicing_register_continuity_weight": 1.15,
            "altered_dominant_source_weight_calibration": {
                "version": "v2_2_88",
                "purpose": "style default intensity/profile for legal altered dominant source selection",
                "default_intensity": "medium",
                "default_scopes": ['resolving_v7', 'secondary_dominants'],
                "source_kinds": ["rooted_color", "rootless_ab", "upper_structure"],
            },
            "altered_dominant_source_weight_biases_by_intensity": {'light': {'rooted_color': 0.06, 'rootless_ab': -0.06, 'upper_structure': -0.06}, 'medium': {'rooted_color': 0.14, 'rootless_ab': 0.04, 'upper_structure': 0.06}, 'high': {'rooted_color': 0.22, 'rootless_ab': 0.1, 'upper_structure': 0.14}, 'full': {'rooted_color': 0.3, 'rootless_ab': 0.18, 'upper_structure': 0.22}},
        },
    )
