from __future__ import annotations


def get_arrangement_policy() -> dict:
    """Medium swing arrangement-level guards.

    The policy remains style-owned, but it only declares guard preferences. The
    default StyleProfile planner applies the guards without letting style files
    emit notes, velocities, durations, or voicings.
    """

    return {
        "default_feel": "medium_swing",
        "avoid_immediate_pattern_repeat": True,
        "avoid_immediate_pattern_category_repeat": True,
        "piano_comping_density_guard": True,
        "piano_region_length_pattern_vocabulary_version": "v2_6_56",
        "piano_region_length_candidate_lookup_policy_version": "v2_6_57",
        "piano_region_length_weight_calibration_policy_version": "v2_6_58",
        "piano_comping_history_continuity_scorer": True,
        "piano_comping_history_continuity_scorer_version": "v2_6_59",
        "piano_comping_active_fill_busy_multi_region_history_scorer": True,
        "piano_comping_active_fill_busy_multi_region_history_scorer_version": "v2_6_67",
        "piano_comping_harmonic_function_policy": True,
        "piano_comping_harmonic_function_policy_version": "v2_6_60",
        "piano_comping_progression_specific_subset_policy": True,
        "piano_comping_progression_specific_subset_policy_version": "v2_6_65",
        "piano_comping_no_4and_delayed_tail_idiom_policy": True,
        "piano_comping_no_4and_delayed_tail_idiom_policy_version": "v2_6_66",
        "piano_expression_policy_v1_numeric_calibration": True,
        "piano_expression_policy_v1_numeric_calibration_version": "v2_6_68",
        "piano_standard_tune_listening_checkpoint": True,
        "piano_standard_tune_listening_checkpoint_version": "v2_6_69",
        "piano_comping_ending_specific_subset_policy": True,
        "piano_comping_ending_specific_subset_policy_version": "v2_6_70",
        "piano_comping_optional_fill_variation_vocabulary_policy": True,
        "piano_comping_optional_fill_variation_vocabulary_policy_version": "v2_6_71",
        "piano_comping_optional_fill_variation_listening_refinement_policy": True,
        "piano_comping_optional_fill_variation_listening_refinement_policy_version": "v2_6_72",
        "piano_comping_phrase_end_fill_context_precision_policy": True,
        "piano_comping_phrase_end_fill_context_precision_policy_version": "v2_6_73",
        "piano_comping_standard_tune_fill_frequency_checkpoint": True,
        "piano_comping_standard_tune_fill_frequency_checkpoint_version": "v2_6_74",
        "medium_swing_piano_comping_phase_completion_checkpoint": True,
        "medium_swing_piano_comping_phase_completion_checkpoint_version": "v2_6_76",
        "medium_swing_existing_voicing_capability_usage_policy": True,
        "medium_swing_existing_voicing_capability_usage_policy_version": "v2_6_77",
        "medium_swing_existing_voicing_capability_low_register_clarity_guard": True,
        "medium_swing_existing_voicing_capability_low_register_clarity_guard_version": "v2_6_78",
        "medium_swing_full_band_listening_checkpoint": True,
        "medium_swing_full_band_listening_checkpoint_version": "v2_6_79",
        "piano_comping_two_beat_region_density_relief_policy": True,
        "piano_comping_two_beat_region_density_relief_policy_version": "v2_6_80",
        "piano_region_first_anticipation_compatibility_checkpoint": True,
        "piano_region_first_anticipation_compatibility_checkpoint_version": "v2_6_61",
        "piano_region_first_coverage_guard": True,
        "piano_region_first_coverage_guard_version": "v2_6_62",
        "piano_region_length_pattern_vocabulary_contract": "Medium Swing piano comping is selected from ChordRegion-local 1/2/4-beat pitchless rhythm cells; no bar-level two-chord-bar pattern path is used.",
        "piano_region_length_candidate_lookup_contract": "ChordRegion duration routes candidate lookup to 1/2/4-beat region-local pattern families before weighted sampling; inactive v2_6_56 vocabulary is activated only inside its matching region-length family.",
        "piano_region_length_weight_calibration_contract": "Medium Swing piano comping keeps stable cells primary, offbeat conversation secondary, active cells controlled, and native tail-push cells rare; calibration is applied inside the existing region-length pattern library, not through a parallel selector.",
        "piano_comping_history_continuity_contract": "Medium Swing piano comping applies a lightweight history scorer to the existing region-length candidate pool, penalizing exact repeat, non-stable family repeat, consecutive offbeat/active/tail-push, and rewarding stable reset after active/offbeat; no parallel selector is introduced.",
        "piano_comping_active_fill_busy_multi_region_history_contract": "v2_6_67 extends the existing history scorer in-place with multi-region active/fill/busy/push/tail-push memory, stable reset bonuses, and no-4& delayed-tail recovery after recent push; it remains ChordRegion-first and does not restore bar-first phrase templates.",
        "piano_comping_harmonic_function_contract": "Medium Swing piano comping reweights the existing ChordRegion-length candidate pool by functional motion labels such as predominant_to_dominant, dominant_resolution, tonic_resolution, section_start, section_end, and ending; this remains a multiplier policy before the normal history scorer, not a bar-first/two-chord-bar or parallel selector path.",
        "piano_comping_progression_specific_subset_contract": "Medium Swing piano comping translates V1 major_251/minor_251/two_five/ii_setup priority into a ChordRegion-first preferred subset inside the existing region-length candidate pool; it never restores bar-first/two-chord-bar templates, never chooses voicing, and never writes final expression values.",
        "piano_comping_no_4and_delayed_tail_idiom_contract": "Medium Swing piano comping translates V1 no-4& / delayed-tail preference as region-local candidate reweighting: native 4& tail-push remains available as rare lift, delayed/tail/backbeat cells get only modest bonuses, and routing remains ChordRegion-first.",
        "piano_expression_policy_v1_numeric_calibration_contract": "Medium Swing piano expression calibrates style-owned ExpressionProfile defaults from V1 soft_hold/light_stab/accent_stab/backbeat_hold/final_hold numeric ranges; pattern files remain semantic-only and never write velocity/duration/pedal.",
        "piano_standard_tune_listening_checkpoint_contract": "v2_6_69 is a behavior-preserving standard-tune listening checkpoint after v2_6_67 history scoring and v2_6_68 expression calibration; it adds audit/demo coverage only and does not change pattern, voicing, expression, API, Agent, or HarmonyOS runtime behavior.",
        "piano_comping_ending_specific_subset_contract": "v2_6_70 reweights final-bar Medium Swing piano comping candidates inside the existing ChordRegion-length pool toward stable region-start settling and away from active/4& push; it does not add an ending selector, new vocabulary, voicing logic, or final expression values.",
        "piano_comping_optional_fill_variation_vocabulary_contract": "v2_6_71 activates a very small optional fill/variation vocabulary inside the existing ChordRegion-length Medium Swing piano pool. These candidates stay pitchless, low-weight, context-reweighted, and guarded by the v2_6_67 active/fill/busy history scorer; no parallel fill selector, voicing logic, or final expression values are introduced.",
        "piano_comping_optional_fill_variation_listening_refinement_contract": "v2_6_72 keeps the v2_6_71 optional vocabulary unchanged and only refines context/history multipliers after user review: light variation remains low-intrusion, transition fill is more phrase/section/turnaround-aware, busy fill stays near-blocked unless explicitly high-energy and history-safe.",
        "piano_comping_phrase_end_fill_context_precision_contract": "v2_6_73 keeps the v2_6_71/v2_6_72 optional fill vocabulary unchanged and only sharpens where the existing transition-fill candidate receives support: explicit phrase ends, section tails, and 4/8-bar phrase tails are favored, while harmonic-transition-only regions are downweighted. No phrase engine, fill selector, new vocabulary, voicing logic, or final expression values are introduced.",
        "piano_comping_standard_tune_fill_frequency_checkpoint_contract": "v2_6_74 is a behavior-preserving standard-tune fill-frequency checkpoint after user approval of v2_6_71/72/73. It measures optional variation/fill frequency, phrase-tail targeting, and active/fill/busy continuity on 3-chorus standard demos without changing weights, adding vocabulary, creating a fill selector, or touching voicing/expression/API/Agent/HarmonyOS.",
        "medium_swing_piano_comping_phase_completion_checkpoint_contract": "v2_6_76 is a behavior-preserving stage-completion checkpoint for the v2_6_56 through v2_6_74 Medium Swing piano comping line. It confirms ChordRegion-first vocabulary, history continuity, expression-hint handoff, ending stability, optional fill low-intrusion, and pattern/voicing/expression separation before returning to voicing or broader listening work; it does not change weights, add vocabulary, create a selector, or touch API/Agent/HarmonyOS.",
        "medium_swing_existing_voicing_capability_usage_policy_contract": "v2_6_77 does not modify core voicing internals. Medium Swing keeps ordinary runtime comping on existing OPEN/DROP 4-note policy by default; when explicitly enabled through style intent or voicing_override metadata, event-scoped style policy may request already-existing grouped SPREAD 5/6-note support for final-chorus section tails or ending climax regions.",
        "medium_swing_existing_voicing_capability_low_register_clarity_guard_contract": "v2_6_78 keeps v2_6_77 as an explicit style-intent capability but routes optional grouped-SPREAD 5/6-note usage through the existing spread low-register density guard: in full-band/bass-present usage, no more than one piano note may sit below C3. This is a style/event metadata request, not a core voicing implementation change.",
        "medium_swing_full_band_listening_checkpoint_contract": "v2_6_79 is a behavior-preserving full-band listening checkpoint after the v2_6_78 low-register clarity guard. It generates and audits 3-chorus Medium Swing demos with piano, bass, and drums enabled to confirm whole-band track presence, piano/bass low-register clarity, optional 5/6-note intrusion, optional fill frequency, bass continuity, dry swing pedal behavior, and ending stability. It does not change pattern, voicing internals, expression numbers, API, Agent, or HarmonyOS.",
        "piano_comping_two_beat_region_density_relief_policy_contract": "v2_6_80 relaxes Medium Swing piano comping in dense 2-beat ChordRegions such as Autumn Leaves: it favors simple region-start anchors, downweights multi-touch/offbeat short-region cells, and preserves previous-region tail space so the generic AnticipationResolver can move next-region beat-1 events to the prior local 2& when probability permits. It stays inside the existing ChordRegion-local candidate weighting path and does not add vocabulary, restore bar-first/two-chord-bar routing, touch voicing/expression internals, or affect API/Agent/HarmonyOS behavior.",
        "piano_comping_ending_specific_subset_milestone": "v2_6_70_medium_swing_ending_specific_region_context_candidate_subset_policy",
        "piano_comping_optional_fill_variation_vocabulary_milestone": "v2_6_71_medium_swing_optional_fill_variation_vocabulary_activation",
        "piano_comping_optional_fill_variation_listening_refinement_milestone": "v2_6_72_medium_swing_fill_variation_listening_refinement_after_user_review",
        "piano_comping_phrase_end_fill_context_precision_milestone": "v2_6_73_medium_swing_phrase_end_fill_context_precision",
        "piano_comping_standard_tune_fill_frequency_checkpoint_milestone": "v2_6_74_medium_swing_standard_tune_fill_frequency_checkpoint",
        "medium_swing_piano_comping_phase_completion_checkpoint_milestone": "v2_6_76_medium_swing_piano_comping_phase_completion_checkpoint",
        "medium_swing_existing_voicing_capability_usage_policy_milestone": "v2_6_77_medium_swing_existing_voicing_capability_usage_policy",
        "medium_swing_existing_voicing_capability_low_register_clarity_guard_milestone": "v2_6_78_medium_swing_existing_voicing_capability_low_register_clarity_guard",
        "medium_swing_full_band_listening_checkpoint_milestone": "v2_6_79_medium_swing_full_band_listening_checkpoint_after_low_register_clarity_guard",
        "piano_comping_two_beat_region_density_relief_policy_milestone": "v2_6_80_medium_swing_two_beat_region_density_relief_and_anticipation_audit",
        "piano_region_first_anticipation_compatibility_contract": "Medium Swing anticipation remains region-first: the previous ChordRegion tail slot is computed from region duration, so 4-beat regions use local 4&/3.5, 2-beat regions use local 2&/1.5, and short regions are never forced through a bar-first 4& assumption.",
        "piano_region_first_coverage_guard_contract": "Medium Swing CoverageGuard is region-first and backup-only: it checks selected ChordRegion-local piano comping plans after pattern policy, stamps coverage audit metadata when the region already has piano presence, and inserts a single pitchless region-start fallback anchor only when a ChordRegion would otherwise be uncovered; it never replaces region-length pattern policy or uses bar-first/two-chord-bar routing.",
        "milestone": "v2_6_69_medium_swing_piano_standard_tune_listening_checkpoint",
    }
