from __future__ import annotations

from jammate_engine.core.voicing import ContentFamily, Disposition, RootSupportPolicy, VoicingPolicy


def get_voicing_policy() -> VoicingPolicy:
    return VoicingPolicy(
        root_support=RootSupportPolicy.ROOTLESS_ALLOWED,
        allowed_content=(ContentFamily.ROOTLESS_A, ContentFamily.ROOTLESS_B, ContentFamily.ROOTED_COLOR, ContentFamily.SEVENTH_BASIC, ContentFamily.SHELL),
        preferred_content=ContentFamily.ROOTLESS_A,
        content_family_weights={
            ContentFamily.ROOTLESS_B.value: 0.18,
            ContentFamily.ROOTED_COLOR.value: -0.03,
            ContentFamily.SEVENTH_BASIC.value: -0.05,
            ContentFamily.SHELL.value: -0.45,
        },
        source_family_weights={},
        source_family_weights_by_gate={
            "chord_symbol_only": {
                "root_third_fifth_root": 0.04,
                "third_fifth_root_third": 0.02,
                "fifth_root_third_fifth": 0.00,
                "root_second_fifth_root": 0.02,
                "second_fifth_root_second": 0.00,
                "fifth_root_second_fifth": -0.02,
                "root_fourth_fifth_root": 0.01,
                "fourth_fifth_root_fourth": -0.01,
                "fifth_root_fourth_fifth": -0.03,
                "root_third_fifth": 0.02,
                "root_second_fifth": 0.01,
                "root_fourth_fifth": 0.00,
                "root_third_sixth": 0.04,
                "root_third_ninth": 0.06,
                "third_seventh_fifth": 0.08,
                "third_seventh_root": -0.14,
                # Plain seventh/sixth symbols should remain grounded, but not
                # dominate over rootless/color candidates once a gate opens.
                "root_third_fifth_seventh": -0.02,
                "root_third_fifth_sixth": -0.01,
                "root_fourth_fifth_seventh": -0.04,
            },
            "harmonic_expansion": {
                "root_third_sixth": 0.06,
                "root_third_ninth": 0.08,
                "root_third_seventh": 0.04,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": -0.02,
                "third_seventh_thirteenth": 0.02,
                "third_seventh_altered_color": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.16,
                # Medium swing can take tasteful jazz color under expansion,
                # with with_5 as the default rootless color and with_13 as a
                # secondary flavor rather than a constant thick texture.
                "with_5": 0.14,
                "third_fifth_seventh_ninth": 0.14,
                "with_13": -0.06,
                "third_thirteenth_seventh_ninth": -0.06,
                "root_third_fifth_ninth": 0.06,
                "root_third_seventh_ninth": 0.06,
                "root_third_sixth_ninth": 0.05,
                "root_third_seventh_thirteenth": 0.04,
                "root_third_seventh_eleventh": -0.03,
                "third_fifth_seventh_eleventh": -0.04,
                "third_eleventh_fifth_seventh": -0.04,
                "third_seventh_ninth_eleventh": -0.02,
                "root_third_seventh_altered_color": 0.12,
                "altered_dominant_rootless": 0.12,
                "third_seventh_altered_color_a_altered_color_b": 0.12,
            },
            "explicit_chart_color": {
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "root_second_fifth": 0.04,
                "root_fourth_fifth": 0.04,
                "third_seventh_ninth": 0.12,
                "third_seventh_eleventh": 0.06,
                "third_seventh_thirteenth": 0.08,
                "third_seventh_altered_color": 0.14,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.12,
                # When the chart writes color, express it.  13 and altered
                # dominant sources become more acceptable here than in pure
                # expansion mode because they are chart fidelity, not gratuitous
                # extra color.
                "with_5": 0.10,
                "third_fifth_seventh_ninth": 0.10,
                "with_13": 0.08,
                "third_thirteenth_seventh_ninth": 0.08,
                "third_thirteenth_seventh_fifth": 0.06,
                "root_third_fifth_ninth": 0.08,
                "root_third_seventh_ninth": 0.08,
                "root_third_sixth_ninth": 0.08,
                "root_third_seventh_thirteenth": 0.10,
                "root_third_seventh_eleventh": 0.05,
                "third_fifth_seventh_eleventh": 0.04,
                "third_eleventh_fifth_seventh": 0.04,
                "third_seventh_ninth_eleventh": 0.06,
                "root_third_seventh_altered_color": 0.16,
                "altered_dominant_rootless": 0.16,
                "third_seventh_altered_color_a_altered_color_b": 0.16,
            },
            "explicit_chart_color_plus_harmonic_expansion": {
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": 0.04,
                "third_seventh_thirteenth": 0.06,
                "third_seventh_altered_color": 0.14,
                "third_seventh_fifth": 0.03,
                "third_seventh_root": -0.14,
                # Preserve chart-written color first; keep additional expansion
                # slightly calmer than explicit-only to avoid every rich chart
                # symbol becoming over-modern.
                "with_5": 0.10,
                "third_fifth_seventh_ninth": 0.10,
                "with_13": 0.02,
                "third_thirteenth_seventh_ninth": 0.02,
                "third_thirteenth_seventh_fifth": 0.04,
                "root_third_fifth_ninth": 0.08,
                "root_third_seventh_ninth": 0.08,
                "root_third_sixth_ninth": 0.08,
                "root_third_seventh_thirteenth": 0.08,
                "root_third_seventh_eleventh": 0.04,
                "third_fifth_seventh_eleventh": 0.03,
                "third_eleventh_fifth_seventh": 0.03,
                "third_seventh_ninth_eleventh": 0.05,
                "root_third_seventh_altered_color": 0.16,
                "altered_dominant_rootless": 0.16,
                "third_seventh_altered_color_a_altered_color_b": 0.16,
            },
        },
        low_priority_degrees=("#11",),
        low_priority_degree_penalty=0.45,
        preferred_disposition=Disposition.OPEN,
        allowed_dispositions=(Disposition.OPEN, Disposition.CLOSED),
        preferred_density=4,
        min_density=3,
        max_density=5,
        register_low=48,
        register_high=76,
        right_hand_low=55,
        right_hand_high=76,
        top_voice_low=60,
        top_voice_high=72,
        comfort_register_low=56,
        comfort_register_high=69,
        max_voicing_span=22,
        max_top_voice_leap=7,
        voice_leading_weight=1.25,
        top_voice_weight=1.35,
        register_guard_weight=1.15,
        selector_temperature=0.08,
        selection_pool_size=3,
        metadata={
            "style": "medium_swing",
            "default_texture": "open_swing",
            "voicing_texture_state_runtime_filtering_enabled": True,
            "voicing_texture_scope_runtime_enabled": True,
            "voicing_texture_runtime_scope_type": "section",
            "voicing_texture_contrast_planning_enabled": True,
            "voicing_texture_contrast_planning_contract": "v2_2_38_medium_swing_generic_open_fallback_only",
            "voicing_texture_method_weight_shaping_enabled": True,
            "voicing_texture_method_weight_shaping_contract": "v2_2_38_medium_swing_generic_open_fallback_only",
            "primary_texture_family": "open",
            "allowed_texture_families": ["open"],
            "family_stickiness": 0.96,
            "method_stickiness": 0.74,
            "texture_runtime_contract": "v2_2_38_medium_swing_generic_open_fallback_only",
            "texture_runtime_milestone": "v2_2_38_medium_swing_generic_open_fallback_only",
            "texture_state_rescue_nearest_motion_enabled": True,
            "texture_state_rescue_nearest_motion_contract": "v2_2_29; explicit rescue pools collapse to the nearest previous voicing before weighted selection",
            "texture_scope_runtime_contract": "v2_2_38; Medium Swing derives VoicingTextureState at section scope from chord-region metadata before candidate filtering",
            "texture_contrast_planning_contract": "v2_2_38; bridge and final chorus shape OPEN-method selector priors while runtime family remains OPEN",
            "milestone": "v2_1_43_closed_source_weight_finalization",
            "medium_swing_existing_voicing_capability_usage_policy": {
                "version": "v2_6_77",
                "available": True,
                "enabled": False,
                "activation": "explicit_intent_or_voicing_override_only",
                "scope": "event_scoped_style_policy_only",
                "ordinary_body": "keep_open_drop_4note",
                "authorized_scenes": ["final_chorus_section_tail_support", "final_ending_climax"],
                "requested_existing_contracts": ["spread_2plus3_contract", "spread_2plus4_contract", "spread_3plus3_contract"],
                "low_register_clarity_guard_version": "v2_6_78",
                "low_register_clarity_guard_enabled": True,
                "low_register_clarity_threshold": 48,
                "low_register_clarity_max_notes_below": 1,
                "low_register_clarity_contract": "when optional Medium Swing 5/6-note grouped SPREAD is explicitly enabled, reuse the existing spread low-register density guard so full-band piano does not stack more than one note below C3",
                "bass_piano_interaction_guard_version": "v2_6_82",
                "bass_piano_interaction_guard_enabled": True,
                "bass_piano_interaction_register_floor": 48,
                "bass_piano_interaction_spread_root_bass_anchor_low": 48,
                "bass_piano_interaction_spread_root_bass_anchor_high": 60,
                "bass_piano_interaction_spread_root_bass_anchor_target": 54,
                "bass_piano_interaction_guard_contract": "when explicitly enabled 5/6-note grouped SPREAD is used with bass present, request the existing SPREAD candidate pool from C3+ foundation registers so piano does not duplicate or crowd the bass walking foundation; this remains style/event metadata, not a core voicing implementation change",
                "no_core_voicing_change": True,
                "ordinary_runtime_default": False,
            },
            "medium_swing_existing_voicing_capability_usage_policy_version": "v2_6_77",
            "medium_swing_existing_voicing_capability_low_register_clarity_guard_version": "v2_6_78",
            "medium_swing_existing_voicing_capability_low_register_clarity_guard_enabled": True,
            "medium_swing_bass_piano_interaction_guard_version": "v2_6_82",
            "medium_swing_bass_piano_interaction_guard_enabled": True,
            "medium_swing_existing_voicing_capability_boundary": "style policy may request existing grouped SPREAD 5/6-note support in sparse final support scenes; core voicing internals remain unchanged",
            "content_bias": "quality_valid_rootless_with_gated_rooted_color_and_shell_rare",
            "low_priority_color_rule": "ordinary #11 is de-emphasized unless explicit in the chord symbol",
            "open_projection_method_pool": ["generic_open", "drop2", "drop3", "drop2_and_4"],
            "disposition_method_weights": {
                "family": {"closed": 0.30, "open": 0.70, "spread": 0.00},
                "open": {"generic_open": 0.0, "drop2": 0.52, "drop3": 0.38, "drop2_and_4": 0.10},
                "spread": {"lower_upper_grouped": 0.55, "foundation_projection": 0.20, "root_anchored": 0.15, "root_10th_projection": 0.10},
            },
            "disposition_method_weights_enabled_for_scoring": True,
            "runtime_filter_failed_register_guard_candidates": True,
            "disposition_method_weight_contract": "runtime_pilot_v2_2_20; Medium Swing consumes OPEN drop-family method weights in the selector",
            "voicing_texture_state_runtime_contract": "v2_2_38; Medium Swing consumes section-scoped VoicingTextureState; generic_open is fallback-only while bridge/final-chorus contrast shapes DROP-family OPEN-method weights",
            "medium_swing_open_drop_method_lock_calibration_version": "v2_6_45",
            "medium_swing_open_drop_method_lock_calibration_contract": "OPEN family remains locked; generic_open remains fallback-only; drop2_and_4 is a controlled low-frequency color, not a default body",
            "medium_swing_open_drop_method_lock_calibration_target": {
                "drop2_and_4_total_ratio_max": 0.20,
                "bridge_drop3_ratio_gt_baseline": True,
                "final_drop3_ratio_gt_baseline": True,
                "normal_runtime_generic_open_ratio": 0.0,
            },
            "medium_swing_open_drop_voice_leading_continuity_version": "v2_6_46",
            "medium_swing_open_drop_voice_leading_continuity_contract": "observational checkpoint only; method switches and section boundaries must stay smooth before any further drop-family weight changes",
            "medium_swing_open_drop_voice_leading_continuity_thresholds": {
                "top_motion_max_abs": 7,
                "low_motion_max_abs": 8,
                "avg_motion_max": 6.0,
                "span_jump_max_abs": 8,
                "warning_events": 0,
            },
            "medium_swing_open_drop_section_boundary_review_version": "v2_6_47",
            "medium_swing_open_drop_section_boundary_review_contract": "observational checkpoint only; section-boundary entry methods should remain readable with drop2/drop3, while drop2&4 stays inside phrases as low-frequency color",
            "medium_swing_open_drop_section_boundary_review_thresholds": {
                "boundary_events_min": 6,
                "drop2_and_4_entry_events": 0,
                "warning_events": 0,
                "top_motion_max_abs": 7,
                "low_motion_max_abs": 8,
                "avg_motion_max": 6.0,
            },
            "medium_swing_phrase_scope_method_continuity_version": "v2_6_48",
            "medium_swing_phrase_scope_method_continuity_contract": "observational checkpoint only; derive section-local four-region phrase windows from realized OPEN drop-family events before deciding whether a future phrase-level method lock policy is needed",
            "medium_swing_phrase_scope_method_continuity_thresholds": {
                "phrase_scope_events_min": 20,
                "method_switch_ratio_max": 0.70,
                "drop2_and_4_run_max": 2,
                "high_motion_switch_events": 0,
                "avg_motion_max": 6.0,
            },
            "progression_voicing_method_lock_policy_version": "v2_6_116",
            "progression_voicing_method_lock_policy_enabled": True,
            "progression_voicing_method_lock_policy_contract": "style-neutral runtime seed/follow policy for local ii-V, V-I, and ii-V-I OPEN drop-family method continuity; Medium Swing keeps v2_6_49 fields as compatibility aliases",
            "progression_voicing_method_lock_policy_target": {
                "locked_pair_types": ["ii_v", "minor_ii_v", "v_i_major", "v_i_minor", "dominant_to_tonic"],
                "propagated_seed_methods": ["drop2", "drop3"],
                "non_propagated_color_methods": ["drop2_and_4", "generic_open"],
                "runtime_filtering_enabled": True,
                "same_texture_scope_only": True,
            },
            "progression_four_note_orientation_alignment_policy_version": "v2_6_117",
            "progression_four_note_orientation_alignment_policy_enabled": True,
            "progression_four_note_orientation_alignment_policy_contract": "style-neutral progression orientation continuity for eligible 4-note source candidates after harmonic expansion/altered source selection and after method-lock scope establishment; Medium Swing keeps v2_6_50/v2_6_51 fields as compatibility aliases",
            "dominant_altered_source_pool_policy_version": "v2_6_118",
            "dominant_altered_source_pool_policy_enabled": True,
            "dominant_altered_source_pool_policy_contract": "style-neutral additive source-candidate policy: explicit altered dominant symbols stay altered-only for chart fidelity; plain dominants authorized by harmonic expansion + altered policy keep ordinary 9/13 sources and add altered sources before AB/method/projection",
            "dominant_altered_source_pool_policy_target": {
                "explicit_altered_chart_symbols": "altered_only_chart_fidelity",
                "plain_authorized_dominants": "ordinary_9_13_plus_altered_pool",
                "selection_owner": "source_balance_and_altered_intensity_bias",
                "does_not_apply_post_voicing_note_alteration": True,
                "does_not_change_projection": True,
            },
            "progression_four_note_orientation_alignment_policy_target": {
                "scope": "same_texture_scope_local_functional_pair",
                "families": ["basic_4note", "rooted_color_4note", "rootless_ab"],
                "orientation_motion": "A_to_B__B_to_A",
                "mode": "strict_when_matching_candidate_available",
                "runtime_filtering_enabled": True,
                "does_not_force_content_family_change": True,
                "does_not_apply_post_voicing_note_alteration": True,
            },
            "medium_swing_phrase_scope_method_lock_policy_version": "v2_6_49",
            "medium_swing_phrase_scope_method_lock_policy_enabled": True,
            "medium_swing_phrase_scope_method_lock_policy_contract": "runtime seed/follow policy for local ii-V, V-I, and ii-V-I OPEN drop-family method continuity; reuses core harmonic motion and existing method-lock filtering; propagates only DROP2/DROP3, never DROP2&4 as a phrase body",
            "medium_swing_phrase_scope_method_lock_policy_target": {
                "locked_pair_types": ["ii_v", "minor_ii_v", "v_i_major", "v_i_minor", "dominant_to_tonic"],
                "propagated_seed_methods": ["drop2", "drop3"],
                "non_propagated_color_methods": ["drop2_and_4", "generic_open"],
                "runtime_filtering_enabled": True,
                "same_texture_scope_only": True,
            },
            "medium_swing_four_note_rotation_alignment_version": "v2_6_51",
            "medium_swing_four_note_rotation_alignment_enabled": True,
            "medium_swing_four_note_rotation_alignment_contract": "runtime follow policy for generic 4-note source rotations inside the same local ii-V, V-I, or ii-V-I method-lock scope; basic/rooted 1357-like rotations follow inversion+2 ABA/BAB mapping, while rootless A/B remains a specialized child family that flips A/B while keeping its canonical rootless inversion index",
            "medium_swing_four_note_rotation_alignment_target": {
                "scope": "same_texture_scope_local_functional_pair",
                "families": ["basic_4note", "rooted_color_4note", "rootless_ab"],
                "basic_rooted_motion": "1357_to_5713__3571_to_7135__5713_to_1357__7135_to_3571",
                "rootless_motion": "flip_A_B_while_preserving_content_type_and_rootless_inversion_index",
                "mode": "strict_when_matching_candidate_available",
                "runtime_filtering_enabled": True,
                "does_not_force_content_family_change": True,
            },
            "medium_swing_rootless_ab_orientation_alignment_version": "v2_6_50",
            "medium_swing_rootless_ab_orientation_alignment_enabled": True,
            "medium_swing_rootless_ab_orientation_alignment_contract": "compatibility alias for v2_6_50 rootless A/B audit; generic v2_6_51 four-note rotation alignment is the primary mechanism",
            "medium_swing_rootless_ab_orientation_alignment_target": {
                "scope": "same_texture_scope_local_functional_pair",
                "desired_motion": "flip_A_B_while_preserving_content_type_and_inversion_index",
                "mode": "strict_when_matching_candidate_available",
                "runtime_filtering_enabled": True,
                "does_not_force_rootless_when_seed_is_not_rootless": True,
            },
            "medium_swing_same_chord_reattack_comping_reuse_version": "v2_6_52",
            "medium_swing_same_chord_reattack_comping_reuse_enabled": True,
            "medium_swing_same_chord_reattack_comping_reuse_contract": "behavior-preserving audit alias over the existing one-default-voicing-per-chord-region cache; repeated Medium Swing comping hits reuse the cached region voicing unless a gesture explicitly requests fresh revoicing",
            "medium_swing_same_chord_reattack_comping_reuse_target": {
                "scope": "same_chord_region",
                "cache_contract": "one_default_voicing_selection_per_chord_region_until_explicit_gesture_revoices",
                "fresh_revoicing_escape_hatches": ["force_fresh_voicing", "revoice_within_region"],
                "default_same_region_behavior": "reuse_cached_voicing_exactly",
                "does_not_change_pattern_expression_anticipation_or_midi": True,
            },
            "medium_swing_open_drop_safe_extension_top_register_checkpoint_version": "v2_6_53",
            "medium_swing_open_drop_safe_extension_top_register_checkpoint_enabled": True,
            "medium_swing_open_drop_safe_extension_top_register_checkpoint_contract": "behavior-preserving audit checkpoint after OPEN/DROP method lock, generic 4-note rotation alignment, and same-chord comping reuse; verify top register stays calm and major-seventh safe-extension policy does not introduce unnotated #11",
            "medium_swing_open_drop_safe_extension_top_register_checkpoint_target": {
                "scope": "medium_swing_open_drop_actual_runtime",
                "projection_family": "open",
                "top_note_max_allowed": 72,
                "top_note_ge_75_events": 0,
                "major_seventh_default_preferred_colors": ["9", "13"],
                "major_seventh_sharp11_default": "disabled_unless_explicit_symbol_or_harmonic_color_intent",
                "register_guard_failed_events": 0,
                "voice_leading_warning_events": 0,
                "behavior_preserving": True,
                "no_runtime_candidate_change": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "medium_swing_deliberate_revoice_gesture_boundary_version": "v2_6_54",
            "medium_swing_deliberate_revoice_gesture_boundary_enabled": True,
            "medium_swing_deliberate_revoice_gesture_boundary_contract": "default same-chord comping reuse remains exact; any same-region fresh voicing must be requested by explicit pitchless event/gesture intent rather than selector randomness",
            "medium_swing_deliberate_revoice_gesture_boundary_target": {
                "scope": "same_chord_region_explicit_gesture_intent",
                "default_behavior": "reuse_cached_region_voicing_exactly",
                "allowed_escape_hatches": ["force_fresh_voicing", "revoice_within_region"],
                "allowed_intent_sources": ["event_metadata", "gesture_metadata"],
                "implicit_revoicing_events": 0,
                "warning_events": 0,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "medium_swing_deliberate_revoice_micro_motion_policy_version": "v2_6_55",
            "medium_swing_deliberate_revoice_micro_motion_policy_enabled": True,
            "medium_swing_deliberate_revoice_micro_motion_policy_contract": "explicit same-chord fresh revoicing may request a constrained micro-motion candidate pool; default repeated comping still reuses cached region voicing and no pattern/expression/MIDI layer creates revoice events",
            "medium_swing_deliberate_revoice_micro_motion_policy_target": {
                "scope": "same_chord_region_explicit_revoice_micro_motion",
                "trigger": "explicit force_fresh_voicing or revoice_within_region plus optional revoice_motion_policy",
                "default_repeated_comping_behavior": "reuse_cached_region_voicing_exactly",
                "allowed_motion_policies": ["micro_motion", "inner_motion", "top_voice_answer"],
                "require_foundation_stable": True,
                "max_low_motion": 0,
                "max_top_motion": 2,
                "max_avg_motion": 2.5,
                "candidate_filtering_mode": "strict_when_safe_micro_motion_candidate_available",
                "fallback_behavior": "preserve_full_pool_with_audit_reason_when_no_safe_candidate",
                "does_not_create_revoice_gestures": True,
                "does_not_change_pattern_anticipation_expression_or_midi": True,
            },
            "medium_swing_deliberate_revoice_micro_motion_max_low_motion": 0,
            "medium_swing_deliberate_revoice_micro_motion_max_top_motion": 2,
            "medium_swing_deliberate_revoice_micro_motion_max_avg_motion": 2.5,
            "medium_swing_deliberate_revoice_micro_motion_require_foundation_stable": True,
            "source_balance_contract": "3_and_4_note_closed_source_weight_contract: four_mode_aware; chord_symbol_only, harmonic_expansion, explicit_chart_color, and explicit_chart_color_plus_harmonic_expansion use separate weights",
            "upper_structure_register_refinement": {
                "version": "v2_2_89",
                "purpose": "swing keeps upper-structure altered color inside a playable comping band",
                "top_soft_high": 72,
                "top_hard_high": 75,
                "average_pitch_soft_high": 67,
                "single_low_note_guard_threshold": 40,
                "max_notes_below_threshold": 1,
            },
            "upper_structure_register_refinement_enabled": True,
            "upper_structure_top_soft_high": 72,
            "upper_structure_top_hard_high": 75,
            "upper_structure_average_pitch_soft_high": 67,
            "low_register_single_note_threshold": 40,
            "max_notes_below_low_register_single_note_threshold": 1,
            "voicing_register_continuity_guard_enabled": True,
            "voicing_register_center_target": 64,
            "voicing_register_center_tolerance": 5,
            "voicing_register_top_soft_high": 76,
            "voicing_register_top_hard_high": 80,
            "voicing_register_low_soft_low": 45,
            "voicing_register_low_hard_low": 41,
            "voicing_register_top_motion_soft_limit": 5,
            "voicing_register_average_motion_soft_limit": 4.5,
            "voicing_register_continuity_weight": 0.75,
            "altered_dominant_source_weight_calibration": {
                "version": "v2_2_88",
                "purpose": "style default intensity/profile for legal altered dominant source selection",
                "default_intensity": "high",
                "default_scopes": ['resolving_v7', 'secondary_dominants'],
                "source_kinds": ["rooted_color", "rootless_ab", "upper_structure"],
            },
            "altered_dominant_source_weight_biases_by_intensity": {'light': {'rooted_color': 0.06, 'rootless_ab': -0.04, 'upper_structure': -0.08}, 'medium': {'rooted_color': 0.12, 'rootless_ab': 0.04, 'upper_structure': 0.02}, 'high': {'rooted_color': 0.18, 'rootless_ab': 0.12, 'upper_structure': 0.1}, 'full': {'rooted_color': 0.26, 'rootless_ab': 0.22, 'upper_structure': 0.18}},
        },
    )
