from __future__ import annotations

from jammate_engine.core.voicing import ContentFamily, Disposition, RootSupportPolicy, VoicingPolicy


def get_voicing_policy() -> VoicingPolicy:
    return VoicingPolicy(
        root_support=RootSupportPolicy.ROOTLESS_ALLOWED,
        allowed_content=(ContentFamily.ROOTLESS_A, ContentFamily.ROOTLESS_B, ContentFamily.ROOTED_COLOR, ContentFamily.SEVENTH_BASIC, ContentFamily.SHELL),
        preferred_content=ContentFamily.ROOTLESS_A,
        content_family_weights={
            ContentFamily.ROOTLESS_B.value: 0.18,
            ContentFamily.ROOTED_COLOR.value: -0.03,
            ContentFamily.SEVENTH_BASIC.value: -0.05,
            ContentFamily.SHELL.value: -0.45,
        },
        source_family_weights={},
        source_family_weights_by_gate={
            "chord_symbol_only": {
                "root_third_fifth_root": 0.04,
                "third_fifth_root_third": 0.02,
                "fifth_root_third_fifth": 0.00,
                "root_second_fifth_root": 0.02,
                "second_fifth_root_second": 0.00,
                "fifth_root_second_fifth": -0.02,
                "root_fourth_fifth_root": 0.01,
                "fourth_fifth_root_fourth": -0.01,
                "fifth_root_fourth_fifth": -0.03,
                "root_third_fifth": 0.02,
                "root_second_fifth": 0.01,
                "root_fourth_fifth": 0.00,
                "root_third_sixth": 0.04,
                "root_third_ninth": 0.06,
                "third_seventh_fifth": 0.08,
                "third_seventh_root": -0.14,
                # Plain seventh/sixth symbols should remain grounded, but not
                # dominate over rootless/color candidates once a gate opens.
                "root_third_fifth_seventh": -0.02,
                "root_third_fifth_sixth": -0.01,
                "root_fourth_fifth_seventh": -0.04,
            },
            "harmonic_expansion": {
                "root_third_sixth": 0.06,
                "root_third_ninth": 0.08,
                "root_third_seventh": 0.04,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": -0.02,
                "third_seventh_thirteenth": 0.02,
                "third_seventh_altered_color": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.16,
                # Medium swing can take tasteful jazz color under expansion,
                # with with_5 as the default rootless color and with_13 as a
                # secondary flavor rather than a constant thick texture.
                "with_5": 0.14,
                "third_fifth_seventh_ninth": 0.14,
                "with_13": -0.06,
                "third_thirteenth_seventh_ninth": -0.06,
                "root_third_fifth_ninth": 0.06,
                "root_third_seventh_ninth": 0.06,
                "root_third_sixth_ninth": 0.05,
                "root_third_seventh_thirteenth": 0.04,
                "root_third_seventh_eleventh": -0.03,
                "third_fifth_seventh_eleventh": -0.04,
                "third_eleventh_fifth_seventh": -0.04,
                "third_seventh_ninth_eleventh": -0.02,
                "root_third_seventh_altered_color": 0.12,
                "altered_dominant_rootless": 0.12,
                "third_seventh_altered_color_a_altered_color_b": 0.12,
            },
            "explicit_chart_color": {
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "root_second_fifth": 0.04,
                "root_fourth_fifth": 0.04,
                "third_seventh_ninth": 0.12,
                "third_seventh_eleventh": 0.06,
                "third_seventh_thirteenth": 0.08,
                "third_seventh_altered_color": 0.14,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.12,
                # When the chart writes color, express it.  13 and altered
                # dominant sources become more acceptable here than in pure
                # expansion mode because they are chart fidelity, not gratuitous
                # extra color.
                "with_5": 0.10,
                "third_fifth_seventh_ninth": 0.10,
                "with_13": 0.08,
                "third_thirteenth_seventh_ninth": 0.08,
                "third_thirteenth_seventh_fifth": 0.06,
                "root_third_fifth_ninth": 0.08,
                "root_third_seventh_ninth": 0.08,
                "root_third_sixth_ninth": 0.08,
                "root_third_seventh_thirteenth": 0.10,
                "root_third_seventh_eleventh": 0.05,
                "third_fifth_seventh_eleventh": 0.04,
                "third_eleventh_fifth_seventh": 0.04,
                "third_seventh_ninth_eleventh": 0.06,
                "root_third_seventh_altered_color": 0.16,
                "altered_dominant_rootless": 0.16,
                "third_seventh_altered_color_a_altered_color_b": 0.16,
            },
            "explicit_chart_color_plus_harmonic_expansion": {
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "third_seventh_ninth": 0.10,
                "third_seventh_eleventh": 0.04,
                "third_seventh_thirteenth": 0.06,
                "third_seventh_altered_color": 0.14,
                "third_seventh_fifth": 0.03,
                "third_seventh_root": -0.14,
                # Preserve chart-written color first; keep additional expansion
                # slightly calmer than explicit-only to avoid every rich chart
                # symbol becoming over-modern.
                "with_5": 0.10,
                "third_fifth_seventh_ninth": 0.10,
                "with_13": 0.02,
                "third_thirteenth_seventh_ninth": 0.02,
                "third_thirteenth_seventh_fifth": 0.04,
                "root_third_fifth_ninth": 0.08,
                "root_third_seventh_ninth": 0.08,
                "root_third_sixth_ninth": 0.08,
                "root_third_seventh_thirteenth": 0.08,
                "root_third_seventh_eleventh": 0.04,
                "third_fifth_seventh_eleventh": 0.03,
                "third_eleventh_fifth_seventh": 0.03,
                "third_seventh_ninth_eleventh": 0.05,
                "root_third_seventh_altered_color": 0.16,
                "altered_dominant_rootless": 0.16,
                "third_seventh_altered_color_a_altered_color_b": 0.16,
            },
        },
        low_priority_degrees=("#11",),
        low_priority_degree_penalty=0.45,
        preferred_disposition=Disposition.OPEN,
        allowed_dispositions=(Disposition.OPEN, Disposition.CLOSED),
        preferred_density=4,
        min_density=3,
        max_density=5,
        register_low=48,
        register_high=76,
        right_hand_low=55,
        right_hand_high=76,
        top_voice_low=60,
        top_voice_high=72,
        comfort_register_low=56,
        comfort_register_high=69,
        max_voicing_span=22,
        max_top_voice_leap=7,
        voice_leading_weight=1.25,
        top_voice_weight=1.35,
        register_guard_weight=1.15,
        selector_temperature=0.08,
        selection_pool_size=3,
        metadata={
            "style": "medium_swing",
            "default_texture": "open_swing",
            "voicing_texture_state_runtime_filtering_enabled": True,
            "voicing_texture_scope_runtime_enabled": True,
            "voicing_texture_runtime_scope_type": "section",
            "voicing_texture_contrast_planning_enabled": True,
            "voicing_texture_contrast_planning_contract": "v2_2_38_medium_swing_generic_open_fallback_only",
            "voicing_texture_method_weight_shaping_enabled": True,
            "voicing_texture_method_weight_shaping_contract": "v2_2_38_medium_swing_generic_open_fallback_only",
            "primary_texture_family": "open",
            "allowed_texture_families": ["open"],
            "family_stickiness": 0.96,
            "method_stickiness": 0.74,
            "texture_runtime_contract": "v2_2_38_medium_swing_generic_open_fallback_only",
            "texture_runtime_milestone": "v2_2_38_medium_swing_generic_open_fallback_only",
            "texture_state_rescue_nearest_motion_enabled": True,
            "texture_state_rescue_nearest_motion_contract": "v2_2_29; explicit rescue pools collapse to the nearest previous voicing before weighted selection",
            "texture_scope_runtime_contract": "v2_2_38; Medium Swing derives VoicingTextureState at section scope from chord-region metadata before candidate filtering",
            "texture_contrast_planning_contract": "v2_2_38; bridge and final chorus shape OPEN-method selector priors while runtime family remains OPEN",
            "milestone": "v2_1_43_closed_source_weight_finalization",
            "content_bias": "quality_valid_rootless_with_gated_rooted_color_and_shell_rare",
            "low_priority_color_rule": "ordinary #11 is de-emphasized unless explicit in the chord symbol",
            "open_projection_method_pool": ["generic_open", "drop2", "drop3", "drop2_and_4"],
            "disposition_method_weights": {
                "family": {"closed": 0.30, "open": 0.70, "spread": 0.00},
                "open": {"generic_open": 0.0, "drop2": 0.50, "drop3": 0.36, "drop2_and_4": 0.14},
                "spread": {"lower_upper_grouped": 0.55, "foundation_projection": 0.20, "root_anchored": 0.15, "root_10th_projection": 0.10},
            },
            "disposition_method_weights_enabled_for_scoring": True,
            "runtime_filter_failed_register_guard_candidates": True,
            "disposition_method_weight_contract": "runtime_pilot_v2_2_20; Medium Swing consumes OPEN drop-family method weights in the selector",
            "voicing_texture_state_runtime_contract": "v2_2_38; Medium Swing consumes section-scoped VoicingTextureState; generic_open is fallback-only while bridge/final-chorus contrast shapes DROP-family OPEN-method weights",
            "source_balance_contract": "3_and_4_note_closed_source_weight_contract: four_mode_aware; chord_symbol_only, harmonic_expansion, explicit_chart_color, and explicit_chart_color_plus_harmonic_expansion use separate weights",
            "upper_structure_register_refinement": {
                "version": "v2_2_89",
                "purpose": "swing keeps upper-structure altered color inside a playable comping band",
                "top_soft_high": 72,
                "top_hard_high": 75,
                "average_pitch_soft_high": 67,
                "single_low_note_guard_threshold": 40,
                "max_notes_below_threshold": 1,
            },
            "upper_structure_register_refinement_enabled": True,
            "upper_structure_top_soft_high": 72,
            "upper_structure_top_hard_high": 75,
            "upper_structure_average_pitch_soft_high": 67,
            "low_register_single_note_threshold": 40,
            "max_notes_below_low_register_single_note_threshold": 1,
            "voicing_register_continuity_guard_enabled": True,
            "voicing_register_center_target": 64,
            "voicing_register_center_tolerance": 5,
            "voicing_register_top_soft_high": 76,
            "voicing_register_top_hard_high": 80,
            "voicing_register_low_soft_low": 45,
            "voicing_register_low_hard_low": 41,
            "voicing_register_top_motion_soft_limit": 5,
            "voicing_register_average_motion_soft_limit": 4.5,
            "voicing_register_continuity_weight": 0.75,
            "altered_dominant_source_weight_calibration": {
                "version": "v2_2_88",
                "purpose": "style default intensity/profile for legal altered dominant source selection",
                "default_intensity": "high",
                "default_scopes": ['resolving_v7', 'secondary_dominants'],
                "source_kinds": ["rooted_color", "rootless_ab", "upper_structure"],
            },
            "altered_dominant_source_weight_biases_by_intensity": {'light': {'rooted_color': 0.06, 'rootless_ab': -0.04, 'upper_structure': -0.08}, 'medium': {'rooted_color': 0.12, 'rootless_ab': 0.04, 'upper_structure': 0.02}, 'high': {'rooted_color': 0.18, 'rootless_ab': 0.12, 'upper_structure': 0.1}, 'full': {'rooted_color': 0.26, 'rootless_ab': 0.22, 'upper_structure': 0.18}},
        },
    )
