from __future__ import annotations

from jammate_engine.core.voicing import ContentFamily, Disposition, RootSupportPolicy, VoicingPolicy


def get_voicing_policy() -> VoicingPolicy:
    return VoicingPolicy(
        root_support=RootSupportPolicy.ROOTLESS_ALLOWED,
        allowed_content=(
            ContentFamily.ROOTLESS_B,
            ContentFamily.ROOTLESS_A,
            ContentFamily.ROOTED_COLOR,
            ContentFamily.GUIDE_TONE,
            ContentFamily.SEVENTH_BASIC,
        ),
        preferred_content=ContentFamily.ROOTLESS_A,
        content_family_weights={
            ContentFamily.ROOTLESS_B.value: 0.28,
            ContentFamily.ROOTLESS_A.value: 0.06,
            ContentFamily.ROOTED_COLOR.value: -0.08,
            ContentFamily.GUIDE_TONE.value: -0.08,
            ContentFamily.SEVENTH_BASIC.value: -0.18,
        },
        source_family_weights={},
        source_family_weights_by_gate={
            "chord_symbol_only": {
                "root_third_fifth_root": 0.06,
                "third_fifth_root_third": 0.04,
                "fifth_root_third_fifth": 0.02,
                "root_second_fifth_root": 0.07,
                "second_fifth_root_second": 0.04,
                "fifth_root_second_fifth": 0.02,
                "root_fourth_fifth_root": 0.06,
                "fourth_fifth_root_fourth": 0.03,
                "fifth_root_fourth_fifth": 0.00,
                "root_third_fifth": 0.05,
                "root_second_fifth": 0.06,
                "root_fourth_fifth": 0.05,
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.20,
                # Keep bossa clean and light on plain seventh symbols.
                "root_third_fifth_seventh": -0.03,
                "root_third_fifth_sixth": -0.02,
                "root_fourth_fifth_seventh": -0.06,
            },
            "harmonic_expansion": {
                "root_third_sixth": 0.10,
                "root_third_ninth": 0.12,
                "root_third_seventh": 0.02,
                "third_seventh_ninth": 0.06,
                "third_seventh_eleventh": -0.08,
                "third_seventh_thirteenth": -0.06,
                "third_seventh_altered_color": -0.08,
                "third_seventh_fifth": 0.03,
                "third_seventh_root": -0.22,
                # Favor add9 / 6-9 / with_5 clarity; keep 13 and altered colors
                # lower until listening verification confirms they do not feel
                # too heavy for the syncopated texture.
                "with_5": 0.06,
                "third_fifth_seventh_ninth": 0.06,
                "with_13": -0.20,
                "third_thirteenth_seventh_ninth": -0.20,
                "root_third_fifth_ninth": 0.08,
                "root_third_seventh_ninth": 0.08,
                "root_third_sixth_ninth": 0.10,
                "root_third_seventh_thirteenth": -0.04,
                "root_third_seventh_eleventh": -0.08,
                "third_fifth_seventh_eleventh": -0.10,
                "third_eleventh_fifth_seventh": -0.10,
                "third_seventh_ninth_eleventh": -0.08,
                "root_third_seventh_altered_color": -0.10,
                "altered_dominant_rootless": -0.10,
                "third_seventh_altered_color_a_altered_color_b": -0.10,
            },
            "explicit_chart_color": {
                "root_third_sixth": 0.12,
                "root_third_ninth": 0.12,
                "root_second_fifth": 0.08,
                "root_fourth_fifth": 0.06,
                "third_seventh_ninth": 0.08,
                "third_seventh_eleventh": -0.02,
                "third_seventh_thirteenth": 0.04,
                "third_seventh_altered_color": -0.02,
                "third_seventh_fifth": 0.03,
                "third_seventh_root": -0.18,
                "with_5": 0.08,
                "third_fifth_seventh_ninth": 0.08,
                "with_13": -0.04,
                "third_thirteenth_seventh_ninth": -0.04,
                "third_thirteenth_seventh_fifth": -0.02,
                "root_third_fifth_ninth": 0.10,
                "root_third_seventh_ninth": 0.10,
                "root_third_sixth_ninth": 0.12,
                "root_third_seventh_thirteenth": 0.06,
                "root_third_seventh_eleventh": -0.02,
                "third_fifth_seventh_eleventh": -0.04,
                "third_eleventh_fifth_seventh": -0.04,
                "third_seventh_ninth_eleventh": -0.02,
                "root_third_seventh_altered_color": -0.04,
                "altered_dominant_rootless": -0.04,
                "third_seventh_altered_color_a_altered_color_b": -0.04,
            },
            "explicit_chart_color_plus_harmonic_expansion": {
                "root_third_sixth": 0.12,
                "root_third_ninth": 0.12,
                "third_seventh_ninth": 0.06,
                "third_seventh_eleventh": -0.04,
                "third_seventh_thirteenth": 0.02,
                "third_seventh_altered_color": -0.04,
                "third_seventh_fifth": 0.02,
                "third_seventh_root": -0.20,
                "with_5": 0.06,
                "third_fifth_seventh_ninth": 0.06,
                "with_13": -0.08,
                "third_thirteenth_seventh_ninth": -0.08,
                "third_thirteenth_seventh_fifth": -0.04,
                "root_third_fifth_ninth": 0.10,
                "root_third_seventh_ninth": 0.10,
                "root_third_sixth_ninth": 0.12,
                "root_third_seventh_thirteenth": 0.06,
                "root_third_seventh_eleventh": -0.04,
                "third_fifth_seventh_eleventh": -0.06,
                "third_eleventh_fifth_seventh": -0.06,
                "third_seventh_ninth_eleventh": -0.04,
                "root_third_seventh_altered_color": -0.06,
                "altered_dominant_rootless": -0.06,
                "third_seventh_altered_color_a_altered_color_b": -0.06,
            },
        },
        low_priority_degrees=("#11", "#9", "b13"),
        low_priority_degree_penalty=0.35,
        preferred_disposition=Disposition.CLOSED,
        allowed_dispositions=(Disposition.CLOSED, Disposition.OPEN),
        preferred_density=4,
        min_density=3,
        max_density=5,
        register_low=52,
        register_high=76,
        right_hand_low=57,
        right_hand_high=77,
        top_voice_low=60,
        top_voice_high=72,
        comfort_register_low=57,
        comfort_register_high=69,
        max_voicing_span=18,
        max_top_voice_leap=6,
        voice_leading_weight=1.2,
        top_voice_weight=1.15,
        register_guard_weight=1.2,
        selector_temperature=0.07,
        selection_pool_size=3,
        metadata={
            "style": "bossa_nova",
            "default_texture": "light_clean_syncopated_comping",
            "milestone": "v2_1_43_closed_source_weight_finalization",
            "voicing_intent": "compact_4_note_rootless_with_sparse_guide_tone_option",
            "density_rule": "default_4_rich_5_avoid_6_plus",
            "content_bias": "rootless_A_preferred_rootless_B_rescues_gated_rooted_color_available_for_explicit_symbols",
            "low_priority_color_rule": "ordinary #11/#9/b13 are de-emphasized unless explicit in the chord symbol",
            "disposition_method_weights": {
                "family": {"closed": 0.62, "open": 0.33, "spread": 0.05},
                "open": {"generic_open": 0.58, "drop2": 0.30, "drop3": 0.09, "drop2_and_4": 0.03},
                "spread": {"lower_upper_grouped": 0.65, "foundation_projection": 0.20, "root_anchored": 0.10, "root_10th_projection": 0.05},
            },
            "disposition_method_weight_contract": "planning_only_v2_2_10; not consumed by selector yet",
            "source_balance_contract": "3_and_4_note_closed_source_weight_contract: four_mode_aware; clean rooted add9/6-9 is safer than heavy 13/altered rootless in bossa",
            "upper_structure_register_refinement": {
                "version": "v2_2_89",
                "purpose": "bossa keeps upper-structure color light and avoids bright altered stacks",
                "top_soft_high": 70,
                "top_hard_high": 72,
                "average_pitch_soft_high": 66,
                "single_low_note_guard_threshold": 40,
                "max_notes_below_threshold": 1,
            },
            "upper_structure_register_refinement_enabled": True,
            "upper_structure_top_soft_high": 70,
            "upper_structure_top_hard_high": 72,
            "upper_structure_average_pitch_soft_high": 66,
            "low_register_single_note_threshold": 40,
            "max_notes_below_low_register_single_note_threshold": 1,
            "voicing_register_continuity_guard_enabled": True,
            "voicing_register_center_target": 63,
            "voicing_register_center_tolerance": 5,
            "voicing_register_top_soft_high": 74,
            "voicing_register_top_hard_high": 78,
            "voicing_register_low_soft_low": 46,
            "voicing_register_low_hard_low": 42,
            "voicing_register_top_motion_soft_limit": 4,
            "voicing_register_average_motion_soft_limit": 4,
            "voicing_register_continuity_weight": 0.85,
            "altered_dominant_source_weight_calibration": {
                "version": "v2_2_88",
                "purpose": "style default intensity/profile for legal altered dominant source selection",
                "default_intensity": "light",
                "default_scopes": ['resolving_v7'],
                "source_kinds": ["rooted_color", "rootless_ab", "upper_structure"],
            },
            "altered_dominant_source_weight_biases_by_intensity": {'light': {'rooted_color': 0.02, 'rootless_ab': -0.12, 'upper_structure': -0.16}, 'medium': {'rooted_color': 0.06, 'rootless_ab': -0.04, 'upper_structure': -0.08}, 'high': {'rooted_color': 0.1, 'rootless_ab': 0.02, 'upper_structure': -0.02}, 'full': {'rooted_color': 0.16, 'rootless_ab': 0.08, 'upper_structure': 0.04}},
        },
    )
