from __future__ import annotations

from jammate_engine.core.voicing import ContentFamily, Disposition, RootSupportPolicy, VoicingPolicy


BOSSA_HARMONIC_RHYTHM_REGION_CLARITY_AND_VOICING_INTENT_VERSION = "v2_6_103"
BOSSA_OPEN_METHOD_POLICY_CORRECTION_VERSION = "v2_6_104"
BOSSA_VOICING_LISTENING_CHECKPOINT_VERSION = "v2_6_112"
BOSSA_HIGH_COLOR_HARMONIC_EXPANSION_POLICY_VERSION = "v2_6_114"


def get_voicing_policy() -> VoicingPolicy:
    return VoicingPolicy(
        root_support=RootSupportPolicy.ROOTLESS_ALLOWED,
        allowed_content=(
            ContentFamily.ROOTLESS_B,
            ContentFamily.ROOTLESS_A,
            ContentFamily.ROOTED_COLOR,
            ContentFamily.SEVENTH_BASIC,
        ),
        preferred_content=ContentFamily.ROOTLESS_A,
        content_family_weights={
            ContentFamily.ROOTLESS_B.value: 0.28,
            ContentFamily.ROOTLESS_A.value: 0.06,
            ContentFamily.ROOTED_COLOR.value: -0.08,
            ContentFamily.SEVENTH_BASIC.value: -0.12,
        },
        source_family_weights={},
        source_family_weights_by_gate={
            "chord_symbol_only": {
                "root_third_fifth_root": 0.06,
                "third_fifth_root_third": 0.04,
                "fifth_root_third_fifth": 0.02,
                "root_second_fifth_root": 0.07,
                "second_fifth_root_second": 0.04,
                "fifth_root_second_fifth": 0.02,
                "root_fourth_fifth_root": 0.06,
                "fourth_fifth_root_fourth": 0.03,
                "fifth_root_fourth_fifth": 0.00,
                "root_third_fifth": 0.05,
                "root_second_fifth": 0.06,
                "root_fourth_fifth": 0.05,
                "root_third_sixth": 0.08,
                "root_third_ninth": 0.10,
                "third_seventh_fifth": 0.04,
                "third_seventh_root": -0.20,
                # Keep bossa clean and light on plain seventh symbols.
                "root_third_fifth_seventh": -0.03,
                "root_third_fifth_sixth": -0.02,
                "root_fourth_fifth_seventh": -0.06,
            },
            "harmonic_expansion": {
                "root_third_sixth": 0.10,
                "root_third_ninth": 0.12,
                "root_third_seventh": 0.02,
                "third_seventh_ninth": 0.34,
                "third_seventh_eleventh": 0.18,
                "third_seventh_thirteenth": 0.28,
                "third_seventh_altered_color": 0.12,
                "third_seventh_fifth": 0.03,
                "third_seventh_root": -0.22,
                # Favor add9 / 6-9 / with_5 clarity; keep 13 and altered colors
                # lower until listening verification confirms they do not feel
                # too heavy for the syncopated texture.
                "with_5": 0.42,
                "third_fifth_seventh_ninth": 0.42,
                "with_13": 0.38,
                "third_thirteenth_seventh_ninth": 0.38,
                "root_third_fifth_ninth": 0.26,
                "root_third_seventh_ninth": 0.34,
                "root_third_sixth_ninth": 0.36,
                "root_third_seventh_thirteenth": 0.28,
                "root_third_seventh_eleventh": 0.16,
                "third_fifth_seventh_eleventh": 0.12,
                "third_eleventh_fifth_seventh": 0.12,
                "third_seventh_ninth_eleventh": 0.18,
                "root_third_seventh_altered_color": 0.10,
                "altered_dominant_rootless": 0.34,
                "third_seventh_altered_color_a_altered_color_b": 0.34,
            },
            "explicit_chart_color": {
                "root_third_sixth": 0.12,
                "root_third_ninth": 0.12,
                "root_second_fifth": 0.08,
                "root_fourth_fifth": 0.06,
                "third_seventh_ninth": 0.08,
                "third_seventh_eleventh": -0.02,
                "third_seventh_thirteenth": 0.04,
                "third_seventh_altered_color": -0.02,
                "third_seventh_fifth": 0.03,
                "third_seventh_root": -0.18,
                "with_5": 0.08,
                "third_fifth_seventh_ninth": 0.08,
                "with_13": -0.04,
                "third_thirteenth_seventh_ninth": -0.04,
                "third_thirteenth_seventh_fifth": -0.02,
                "root_third_fifth_ninth": 0.10,
                "root_third_seventh_ninth": 0.10,
                "root_third_sixth_ninth": 0.12,
                "root_third_seventh_thirteenth": 0.06,
                "root_third_seventh_eleventh": -0.02,
                "third_fifth_seventh_eleventh": -0.04,
                "third_eleventh_fifth_seventh": -0.04,
                "third_seventh_ninth_eleventh": -0.02,
                "root_third_seventh_altered_color": -0.04,
                "altered_dominant_rootless": -0.04,
                "third_seventh_altered_color_a_altered_color_b": -0.04,
            },
            "explicit_chart_color_plus_harmonic_expansion": {
                "root_third_sixth": 0.12,
                "root_third_ninth": 0.12,
                "third_seventh_ninth": 0.06,
                "third_seventh_eleventh": -0.04,
                "third_seventh_thirteenth": 0.02,
                "third_seventh_altered_color": -0.04,
                "third_seventh_fifth": 0.02,
                "third_seventh_root": -0.20,
                "with_5": 0.06,
                "third_fifth_seventh_ninth": 0.06,
                "with_13": -0.08,
                "third_thirteenth_seventh_ninth": -0.08,
                "third_thirteenth_seventh_fifth": -0.04,
                "root_third_fifth_ninth": 0.10,
                "root_third_seventh_ninth": 0.10,
                "root_third_sixth_ninth": 0.12,
                "root_third_seventh_thirteenth": 0.06,
                "root_third_seventh_eleventh": -0.04,
                "third_fifth_seventh_eleventh": -0.06,
                "third_eleventh_fifth_seventh": -0.06,
                "third_seventh_ninth_eleventh": -0.04,
                "root_third_seventh_altered_color": -0.06,
                "altered_dominant_rootless": -0.06,
                "third_seventh_altered_color_a_altered_color_b": -0.06,
            },
        },
        low_priority_degrees=("#11", "#9"),
        low_priority_degree_penalty=0.35,
        preferred_disposition=Disposition.OPEN,
        allowed_dispositions=(Disposition.OPEN, Disposition.CLOSED),
        preferred_density=4,
        min_density=4,
        max_density=5,
        register_low=52,
        register_high=76,
        right_hand_low=57,
        right_hand_high=77,
        top_voice_low=60,
        top_voice_high=72,
        comfort_register_low=57,
        comfort_register_high=69,
        max_voicing_span=18,
        max_top_voice_leap=6,
        voice_leading_weight=1.2,
        top_voice_weight=1.15,
        register_guard_weight=1.2,
        selector_temperature=0.07,
        selection_pool_size=3,
        metadata={
            "style": "bossa_nova",
            "progression_voicing_method_lock_policy_version": "v2_6_116",
            "progression_voicing_method_lock_policy_enabled": True,
            "progression_voicing_method_lock_policy_contract": "style-neutral runtime seed/follow policy for local ii-V, V-I, and ii-V-I OPEN drop-family method continuity; Bossa opts in without changing voicing projection/source/selector",
            "progression_voicing_method_lock_policy_target": {
                "locked_pair_types": ["ii_v", "minor_ii_v", "v_i_major", "v_i_minor", "dominant_to_tonic"],
                "propagated_seed_methods": ["drop2", "drop3"],
                "non_propagated_color_methods": ["drop2_and_4", "generic_open"],
                "runtime_filtering_enabled": True,
                "same_texture_scope_only": True,
            },
            "progression_four_note_orientation_alignment_policy_version": "v2_6_117",
            "progression_four_note_orientation_alignment_policy_enabled": True,
            "progression_four_note_orientation_alignment_policy_contract": "style-neutral progression orientation continuity for eligible 4-note source candidates after harmonic expansion/altered source selection and after method-lock scope establishment; Bossa opts in through the neutral policy without style-specific aliases and without changing projection/source/selector",
            "dominant_altered_source_pool_policy_version": "v2_6_118",
            "dominant_altered_source_pool_policy_enabled": True,
            "dominant_altered_source_pool_policy_contract": "style-neutral additive source-candidate policy: explicit altered dominant symbols stay altered-only for chart fidelity; plain dominants authorized by harmonic expansion + altered policy keep ordinary 9/13 sources and add altered sources before AB/method/projection",
            "dominant_altered_source_pool_policy_target": {
                "explicit_altered_chart_symbols": "altered_only_chart_fidelity",
                "plain_authorized_dominants": "ordinary_9_13_plus_altered_pool",
                "selection_owner": "source_balance_and_altered_intensity_bias",
                "does_not_apply_post_voicing_note_alteration": True,
                "does_not_change_projection": True,
            },
            "progression_four_note_orientation_alignment_policy_target": {
                "scope": "same_texture_scope_local_functional_pair",
                "families": ["basic_4note", "rooted_color_4note", "rootless_ab"],
                "orientation_motion": "A_to_B__B_to_A",
                "mode": "strict_when_matching_candidate_available",
                "runtime_filtering_enabled": True,
                "does_not_force_content_family_change": True,
                "does_not_apply_post_voicing_note_alteration": True,
            },
            "default_texture": "open_light_clean_syncopated_comping",
            "milestone": "v2_6_103_bossa_open_voicing_and_taxonomy_cleanup",
            "voicing_intent": "open_main_4_to_5_note_bossa_voicing_no_forced_2_or_3_note_short_region_override",
            "density_rule": "default_4_rich_5_avoid_2_and_3_note_bossa_comping",
            "content_bias": "rootless_A_preferred_rootless_B_rescues_gated_rooted_color_available_for_explicit_symbols",
            "voicing_texture_state_runtime_filtering_enabled": True,
            "primary_texture_family": "open",
            "allowed_texture_families": ["open"],
            "family_stickiness": 0.92,
            "method_stickiness": 0.62,
            "open_projection_methods": ["drop2", "drop3", "drop2_and_4"],
            "disposition_method_weights_enabled_for_scoring": True,
            "bossa_harmonic_rhythm_region_clarity_and_voicing_intent_active": True,
            "bossa_harmonic_rhythm_region_clarity_and_voicing_intent_version": BOSSA_HARMONIC_RHYTHM_REGION_CLARITY_AND_VOICING_INTENT_VERSION,
            "bossa_harmonic_rhythm_region_clarity_and_voicing_intent_no_core_voicing_change": True,
            "bossa_harmonic_rhythm_region_clarity_and_voicing_intent_no_parallel_selector": True,
            "bossa_harmonic_rhythm_region_clarity_and_voicing_intent_contract": (
                "Bossa dense/short ChordRegion clarity remains ChordRegion-first, v2_6_102 removed the old forced 2-note guide-tone / 3-note low-density override, and v2_6_103 makes OPEN the normal Bossa voicing family. "
                "Short regions now keep the normal Bossa 4-to-5-note OPEN-main voicing policy and rely on ordinary core voicing capability plus rhythm/expression clarity, "
                "without building voicing sources, projecting notes, scoring candidates, or restoring bar-first two_chord_bar logic."
            ),
            "bossa_dense_short_region_voicing_intent": {
                "enabled": False,
                "superseded_by": "v2_6_103",
                "scope": "piano_harmonic_events_with_region_duration_at_or_below_2.25_beats_or_dense_harmonic_marks_archetype",
                "normal_voicing_policy_for_short_regions": True,
                "avoid_forced_2_note_guide_tone": True,
                "avoid_forced_3_note_low_density": True,
                "preferred_density": 4,
                "min_density": 4,
                "max_density": 5,
                "preferred_content": ContentFamily.ROOTLESS_A.value,
                "root_support": RootSupportPolicy.ROOTLESS_ALLOWED.value,
                "content_family_weight_delta": {},
                "max_voicing_span": 18,
                "selector_temperature": 0.07,
            },
            "bossa_no_forced_low_density_voicing_policy": {
                "version": "v2_6_103",
                "enabled": True,
                "scope": "all_bossa_piano_harmonic_events_including_short_dense_chord_regions",
                "rule": "Do not force Bossa short/dense ChordRegions to 2-note guide-tone or 3-note low-density voicings; keep the ordinary 4-to-5-note Bossa voicing policy and let the core voicing selector operate normally.",
                "no_parallel_selector": True,
                "no_core_voicing_change": True,
            },
            "bossa_open_voicing_main_policy": {
                "version": "v2_6_103",
                "corrected_by": BOSSA_OPEN_METHOD_POLICY_CORRECTION_VERSION,
                "enabled": True,
                "scope": "all_bossa_piano_harmonic_events",
                "preferred_disposition": "open",
                "allowed_runtime_texture_families": ["open"],
                "open_projection_methods": ["drop2", "drop3", "drop2_and_4"],
                "method_policy": "use_existing_drop_family_consensus; do not promote generic_open into ordinary Bossa runtime",
                "retire_closed_as_default": True,
                "closed_available_only_as_policy_level_compatibility_not_runtime_primary": True,
                "no_spread_grouping": True,
            },
            "bossa_open_method_policy_correction": {
                "version": BOSSA_OPEN_METHOD_POLICY_CORRECTION_VERSION,
                "enabled": True,
                "scope": "all_bossa_piano_open_voicing_candidates",
                "reason": "v2_6_103 incorrectly promoted generic_open into Bossa normal runtime; v2_6_104 removes it from the style method pool and returns method priority to the shared drop-family consensus.",
                "normal_open_projection_methods": ["drop2", "drop3", "drop2_and_4"],
                "drop2_role": "primary_body",
                "drop3_role": "secondary_contrast",
                "drop2_and_4_role": "very_low_frequency_color",
                "generic_open_role": "fallback_or_rescue_only_not_normal_candidate",
                "no_style_local_method_reweighting": True,
                "no_projection_algorithm_change": True,
                "no_source_inventory_change": True,
                "no_parallel_selector": True,
            },
            "retired_ordinary_4note_grouping_metadata_policy": {
                "version": "v2_6_103",
                "enabled": True,
                "rule": "Ordinary 4-note CLOSED/OPEN stacks must not be reported as 1+3 or 2+2 grouped voicings; grouped names are reserved for SPREAD lower/upper contracts.",
                "ordinary_4note_functional_grouping": None,
            },
            "bossa_voicing_listening_checkpoint": {
                "version": BOSSA_VOICING_LISTENING_CHECKPOINT_VERSION,
                "enabled": True,
                "behavior_change": False,
                "scope": "checkpoint the Bossa open-main voicing baseline after no-forced-low-density, open-main, method-policy correction, closed-parent fix, and named-open fallback hardening",
                "completed_versions": ("v2_6_102", "v2_6_103", "v2_6_104", "v2_6_110", "v2_6_111"),
                "preferred_disposition": "open",
                "normal_open_projection_methods": ("drop2", "drop3", "drop2_and_4"),
                "generic_open_role": "fallback_or_rescue_only_not_ordinary_runtime",
                "ordinary_density_range": (4, 5),
                "forced_2_or_3_note_voicing": False,
                "spread_grouped_voicing": False,
                "ordinary_4note_grouping_metadata_retired": True,
                "named_open_parent_boundary": "compact_closed_parent_candidates_for_projection_only",
                "noncompact_parent_silent_fallback_allowed": False,
                "no_new_voicing_ability": True,
                "no_style_local_projection_system": True,
                "no_parallel_selector": True,
                "no_piano_rhythm_expression_bass_drums_api_agent_harmonyos_change": True,
                "recommended_next_task": "v2_6_113_engine_bossa_nova_bass_or_voicing_listening_refinement",
            },
            "bossa_high_color_harmonic_expansion_policy": {
                "version": BOSSA_HIGH_COLOR_HARMONIC_EXPANSION_POLICY_VERSION,
                "enabled_when_harmonic_expansion_enabled": True,
                "scope": "Bossa piano harmonic events only, via harmonic-color request metadata before core voicing resolution",
                "no_core_voicing_change": True,
                "no_projection_or_selector_change": True,
                "expanded_color_target_ratio": 0.80,
                "minor_ii_or_tonic": "prefer m9 / m11 color through existing source inventory",
                "major_tonic": "prefer maj9 / 6-9 / maj13 color",
                "warm_dominant": "prefer 9 / 13",
                "minor_cadence_dominant": "prefer b9 / b13",
                "tritone_sub_dominant": "prefer #11 when the dominant is functioning as subV",
            },
            "low_priority_color_rule": "ordinary #11/#9 are de-emphasized unless explicit or high-color expansion asks for them; b13 is allowed as a Bossa minor-cadence color",
            "disposition_method_weight_contract": "runtime_consumed_style_default_drop_family_consensus_v2_6_104; generic_open_fallback_only",
            "source_balance_contract": "3_and_4_note_closed_source_weight_contract: four_mode_aware; clean rooted add9/6-9 is safer than heavy 13/altered rootless in bossa",
            "upper_structure_register_refinement": {
                "version": "v2_2_89",
                "purpose": "bossa keeps upper-structure color light and avoids bright altered stacks",
                "top_soft_high": 70,
                "top_hard_high": 72,
                "average_pitch_soft_high": 66,
                "single_low_note_guard_threshold": 40,
                "max_notes_below_threshold": 1,
            },
            "upper_structure_register_refinement_enabled": True,
            "upper_structure_top_soft_high": 70,
            "upper_structure_top_hard_high": 72,
            "upper_structure_average_pitch_soft_high": 66,
            "low_register_single_note_threshold": 40,
            "max_notes_below_low_register_single_note_threshold": 1,
            "voicing_register_continuity_guard_enabled": True,
            "voicing_register_center_target": 63,
            "voicing_register_center_tolerance": 5,
            "voicing_register_top_soft_high": 74,
            "voicing_register_top_hard_high": 78,
            "voicing_register_low_soft_low": 46,
            "voicing_register_low_hard_low": 42,
            "voicing_register_top_motion_soft_limit": 4,
            "voicing_register_average_motion_soft_limit": 4,
            "voicing_register_continuity_weight": 0.85,
            "altered_dominant_source_weight_calibration": {
                "version": "v2_2_88",
                "purpose": "style default intensity/profile for legal altered dominant source selection",
                "default_intensity": "light",
                "default_scopes": ['resolving_v7'],
                "source_kinds": ["rooted_color", "rootless_ab", "upper_structure"],
            },
            "altered_dominant_source_weight_biases_by_intensity": {'light': {'rooted_color': 0.02, 'rootless_ab': -0.12, 'upper_structure': -0.16}, 'medium': {'rooted_color': 0.06, 'rootless_ab': -0.04, 'upper_structure': -0.08}, 'high': {'rooted_color': 0.1, 'rootless_ab': 0.02, 'upper_structure': -0.02}, 'full': {'rooted_color': 0.16, 'rootless_ab': 0.08, 'upper_structure': 0.04}},
        },
    )
